package com.croparia.mod.Init;

import com.croparia.mod.Reference;
import com.croparia.mod.Blocks.BlockCloud;
import com.croparia.mod.Blocks.BlockCropMod;
import com.croparia.mod.Blocks.BlockGreenhouse;
import com.croparia.mod.Blocks.BlockIcyPlant;
import com.croparia.mod.Blocks.BlockInfusor;
import com.croparia.mod.Blocks.BlockInfusor2;
import com.croparia.mod.Blocks.BlockObsidianGround;
import com.croparia.mod.Blocks.BlockOreMod;
import com.croparia.mod.Blocks.BlockPlant;
import com.croparia.mod.Blocks.BlockPlantMod;
import com.croparia.mod.Blocks.BlockQuickIce;
import com.croparia.mod.Blocks.BlockReward;
import com.croparia.mod.Blocks.BlockStemMod;
import com.croparia.mod.Blocks.Furnace.BlockCoalFurnace;
import com.croparia.mod.Blocks.Furnace.BlockDiamondFurnace;
import com.croparia.mod.Blocks.Furnace.BlockFireFurnace;
import com.croparia.mod.Blocks.Furnace.BlockGoldFurnace;
import com.croparia.mod.Blocks.Furnace.BlockIronFurnace;
import com.croparia.mod.Blocks.Furnace.BlockLapisFurnace;
import com.croparia.mod.Blocks.Furnace.BlockObsidianFurnace;
import com.croparia.mod.Blocks.Furnace.BlockRedstoneFurnace;
import com.croparia.mod.Blocks.Furnace.BlockRenforcedFurnace;
import com.croparia.mod.Blocks.RitualStand.BlockRitualStand;
import com.croparia.mod.Blocks.RitualStand.BlockRitualStandT2;
import com.croparia.mod.Blocks.RitualStand.BlockRitualStandT3;

import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.init.Blocks;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.fml.relauncher.Side;

@EventBusSubscriber(value = Side.CLIENT, modid = Reference.MOD_ID)
public class ModBlocks
{
	public static final Block ELEMENTAL_STONE = new Block(Material.ROCK).setHardness(1.5F).setResistance(10.0F).setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "elemental_stone").setUnlocalizedName(Reference.MOD_ID + "." + "elemental_stone");
	public static final Block RITUAL_STAND = new BlockRitualStand("ritual_stand");
	public static final Block RITUAL_STAND_t2 = new BlockRitualStandT2("ritual_stand_t2");
	public static final Block RITUAL_STAND_t3 = new BlockRitualStandT3("ritual_stand_t3");
	//Infusor : empty, water, fire, earth, air, elemental
	public static final Block INFUSOR = new BlockInfusor("infusor", true, false, false, false, false, false);
	public static final Block INFUSOR_ELEMENTAL = new BlockInfusor("infusor_elemental", false, false, false, false, false, true);
	public static final Block INFUSOR_WATER = new BlockInfusor("infusor_water", false, true, false, false, false, false);
	public static final Block INFUSOR_FIRE = new BlockInfusor("infusor_fire", false, false, true, false, false, false);
	public static final Block INFUSOR_EARTH = new BlockInfusor("infusor_earth", false, false, false, true, false, false);
	public static final Block INFUSOR_AIR = new BlockInfusor("infusor_air", false, false, false, false, true, false);
	
	public static final Block INFUSOR2 = new BlockInfusor2("infusor2", true, false, false, false, false, false);
	public static final Block INFUSOR2_ELEMENTAL = new BlockInfusor2("infusor2_elemental", false, false, false, false, false, true);
	public static final Block INFUSOR2_WATER = new BlockInfusor2("infusor2_water", false, true, false, false, false, false);
	public static final Block INFUSOR2_FIRE = new BlockInfusor2("infusor2_fire", false, false, true, false, false, false);
	public static final Block INFUSOR2_EARTH = new BlockInfusor2("infusor2_earth", false, false, false, true, false, false);
	public static final Block INFUSOR2_AIR = new BlockInfusor2("infusor2_air", false, false, false, false, true, false);
	
	public static final Block WATER_BLOCK = new Block(Material.ROCK).setHardness(1.5F).setResistance(10.0F).setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "water_block").setUnlocalizedName(Reference.MOD_ID + "." + "water_block");	
	public static final Block WATER_GEM_ORE = new BlockOreMod(Material.ICE, "water_gem_ore");
	public static final Block FIRE_BLOCK = new Block(Material.ROCK).setHardness(1.5F).setResistance(10.0F).setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "fire_block").setUnlocalizedName(Reference.MOD_ID + "." + "fire_block");	
	public static final Block FIRE_GEM_ORE = new BlockOreMod(Material.ROCK, "fire_gem_ore");
	public static final Block EARTH_BLOCK = new Block(Material.ROCK).setHardness(1.5F).setResistance(10.0F).setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "earth_block").setUnlocalizedName(Reference.MOD_ID + "." + "earth_block");	
	public static final Block EARTH_GEM_ORE = new BlockOreMod(Material.GRASS, "earth_gem_ore");
	public static final Block AIR_BLOCK = new Block(Material.ROCK).setHardness(1.5F).setResistance(10.0F).setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "air_block").setUnlocalizedName(Reference.MOD_ID + "." + "air_block");	
	public static final Block AIR_GEM_ORE = new BlockOreMod(Material.GRASS, "air_gem_ore");
	
	public static final Block QUICK_ICE = new BlockQuickIce("quick_ice").setHardness(0.5F);
	public static final Block ICY_PLANT = new BlockIcyPlant("icy_plant");
	public static final Block POISONOUS_ICY_PLANT = new BlockIcyPlant("poisonous_icy_plant");
	public static final Block OBSIDIAN_GROUND = new BlockObsidianGround("obsidian_ground");
	public static final Block FIRED_OBSIDIAN_GROUND = new BlockObsidianGround("fired_obsidian_ground");
	public static final Block QUICK_SAND = new BlockQuickIce("quick_sand").setHardness(0.5F);
	public static final Block BOUNCE_CLOUD = new BlockCloud("bounce_cloud").setHardness(0.5F);
	public static final Block CLOUD = new BlockCloud("cloud").setHardness(0.5F);
	
	public static final Block COAL_CROP = new BlockCropMod("block_crop_coal", Blocks.COAL_BLOCK);
	public static final Block IRON_CROP = new BlockCropMod("block_crop_iron", Blocks.IRON_BLOCK);
	public static final Block GOLD_CROP = new BlockCropMod("block_crop_gold", Blocks.GOLD_BLOCK);
	public static final Block REDSTONE_CROP = new BlockCropMod("block_crop_redstone", Blocks.REDSTONE_BLOCK);
	public static final Block LAPIS_CROP = new BlockCropMod("block_crop_lapis", Blocks.LAPIS_BLOCK);
	public static final Block DIAMOND_CROP = new BlockCropMod("block_crop_diamond", Blocks.DIAMOND_BLOCK);
	public static final Block EMERALD_CROP = new BlockCropMod("block_crop_emerald", Blocks.EMERALD_BLOCK);
	public static final Block ELEMENTAL_CROP = new BlockCropMod("block_crop_elemental", ModBlocks.ELEMENTAL_STONE);
	public static final Block CLAY_CROP = new BlockCropMod("block_crop_clay", Blocks.CLAY);
	public static final Block GLOWSTONE_CROP = new BlockCropMod("block_crop_glowstone", Blocks.GLOWSTONE);
	public static final Block QUARTZ_CROP = new BlockCropMod("block_crop_quartz", Blocks.QUARTZ_BLOCK);
	public static final Block SHARD_CROP = new BlockCropMod("block_crop_shard", Blocks.PRISMARINE);
	public static final Block CRYSTAL_CROP = new BlockCropMod("block_crop_crystal", Blocks.SEA_LANTERN);
	public static final Block PAPER_CROP = new BlockCropMod("block_crop_paper");
	public static final Block SUGAR_CROP = new BlockCropMod("block_crop_sugar");
	public static final Block CHARCOAL_CROP = new BlockCropMod("block_crop_charcoal", Blocks.COAL_BLOCK);
	public static final Block FLINT_CROP = new BlockCropMod("block_crop_flint");
	public static final Block SNOWBALL_CROP = new BlockCropMod("block_crop_snowball", Blocks.SNOW);
	public static final Block FIREWORK_CROP = new BlockCropMod("block_crop_firework");
	public static final Block NETHER_CROP = new BlockCropMod("block_crop_nether", Blocks.NETHER_BRICK);
	public static final Block BOTTLE_CROP = new BlockCropMod("block_crop_bottle", Blocks.GLASS);
	public static final Block TOTEM_CROP = new BlockCropMod("block_crop_totem");
	public static final Block LEAD2_CROP = new BlockCropMod("block_crop_lead2");
	public static final Block NAMETAG_CROP = new BlockCropMod("block_crop_nametag");
	public static final Block XP_CROP = new BlockCropMod("block_crop_xp", Blocks.BEACON);
	public static final Block ENDER_CROP = new BlockCropMod("block_crop_ender");
	public static final Block BONE_CROP = new BlockCropMod("block_crop_bone", Blocks.BONE_BLOCK);
	public static final Block EYE_CROP = new BlockCropMod("block_crop_eye");
	public static final Block POWDER_CROP = new BlockCropMod("block_crop_powder");
	public static final Block BLAZE_CROP = new BlockCropMod("block_crop_blaze");
	public static final Block GHAST_CROP = new BlockCropMod("block_crop_ghast");
	public static final Block MAGMA_CROP = new BlockCropMod("block_crop_magma", Blocks.MAGMA);
	public static final Block SHELL_CROP = new BlockCropMod("block_crop_shell");
	public static final Block SLIME_CROP = new BlockCropMod("block_crop_slime", Blocks.SLIME_BLOCK);
	public static final Block STAR_CROP = new BlockCropMod("block_crop_star");
	public static final Block STRING_CROP = new BlockCropMod("block_crop_string", Blocks.WOOL);
	public static final Block ZOMBIE_CROP = new BlockCropMod("block_crop_zombie");	
	public static final Block APPLE_CROP = new BlockCropMod("block_crop_apple");
	public static final Block GOLDENAPPLE_CROP = new BlockCropMod("block_crop_goldenapple");
	public static final Block BREAD_CROP = new BlockCropMod("block_crop_bread");
	public static final Block EGG_CROP = new BlockCropMod("block_crop_egg");
	public static final Block CLOWNFISH_CROP = new BlockCropMod("block_crop_clownfish");
	public static final Block PUFFERFISH_CROP = new BlockCropMod("block_crop_pufferfish");
	public static final Block COOKIE_CROP = new BlockCropMod("block_crop_cookie");
	public static final Block CHORUS_CROP = new BlockCropMod("block_crop_chorus");
	public static final Block RAWPORC_CROP = new BlockCropMod("block_crop_rawporc");
	public static final Block RAWBEEF_CROP = new BlockCropMod("block_crop_rawbeef");
	public static final Block FISH_CROP = new BlockCropMod("block_crop_fish");
	public static final Block SALMON_CROP = new BlockCropMod("block_crop_salmon");
	public static final Block RAWCHICKEN_CROP = new BlockCropMod("block_crop_rawchicken");
	public static final Block RAWRABBIT_CROP = new BlockCropMod("block_crop_rawrabbit");
	public static final Block RAWMUTTON_CROP = new BlockCropMod("block_crop_rawmutton");	
	public static final Block ORANGE_CROP1 = new BlockCropMod("block_crop_orange"); 
	public static final Block MAGENTA_CROP = new BlockCropMod("block_crop_magenta");
	public static final Block LIGHTBLUE_CROP = new BlockCropMod("block_crop_lightblue");
	public static final Block YELLOW_CROP = new BlockCropMod("block_crop_yellow");
	public static final Block LIME_CROP = new BlockCropMod("block_crop_lime");
	public static final Block PINK_CROP = new BlockCropMod("block_crop_pink");
	public static final Block GRAY_CROP = new BlockCropMod("block_crop_gray");
	public static final Block SILVER_CROP = new BlockCropMod("block_crop_silver");
	public static final Block CYAN_CROP = new BlockCropMod("block_crop_cyan");
	public static final Block PURPLE_CROP = new BlockCropMod("block_crop_purple");
	public static final Block BROWN_CROP = new BlockCropMod("block_crop_brown");
	public static final Block GREEN_CROP = new BlockCropMod("block_crop_green");
	public static final Block RED_CROP = new BlockCropMod("block_crop_red");
	public static final Block BLACK_CROP = new BlockCropMod("block_crop_black");		
	public static final Block VINE_CROP = new BlockCropMod("block_crop_vine");
	public static final Block LILYPAD_CROP = new BlockCropMod("block_crop_lilypad");
	public static final Block TALLGRASS_CROP = new BlockCropMod("block_crop_tallgrass");
	public static final Block LARGEFERN_CROP = new BlockCropMod("block_crop_largefern");
	public static final Block BUSH_CROP = new BlockCropMod("block_crop_bush");
	public static final Block GRASS1_CROP = new BlockCropMod("block_crop_grass1");
	public static final Block FERN_CROP = new BlockCropMod("block_crop_fern");
	public static final Block OAK_CROP = new BlockCropMod("block_crop_oak");
	public static final Block BIRCH_CROP = new BlockCropMod("block_crop_birch");
	public static final Block SPRUCE_CROP = new BlockCropMod("block_crop_spruce");
	public static final Block JUNGLE_CROP = new BlockCropMod("block_crop_jungle");
	public static final Block DARKOAK_CROP = new BlockCropMod("block_crop_darkoak");
	public static final Block ACACIA_CROP = new BlockCropMod("block_crop_acacia");
	public static final Block LEATHER_CROP = new BlockCropMod("block_crop_leather");
	public static final Block FEATHER_CROP = new BlockCropMod("block_crop_feather");
	public static final Block HIDE_CROP = new BlockCropMod("block_crop_hide");
	public static final Block FOOT_CROP = new BlockCropMod("block_crop_foot");
	
	public static final Block ALUMINIUM_CROP = new BlockCropMod("block_crop_aluminium");
    public static final Block BRASS_CROP = new BlockCropMod("block_crop_brass");
    public static final Block BRONZE_CROP = new BlockCropMod("block_crop_bronze");
    public static final Block CHROME_CROP = new BlockCropMod("block_crop_chrome");
    public static final Block COPPER_CROP = new BlockCropMod("block_crop_copper");
    public static final Block ELECTRUM_CROP = new BlockCropMod("block_crop_electrum");
    public static final Block INVAR_CROP = new BlockCropMod("block_crop_invar");
    public static final Block IRIDIUM_CROP = new BlockCropMod("block_crop_iridium");
    public static final Block LEAD_CROP = new BlockCropMod("block_crop_lead");
    public static final Block NICKEL_CROP = new BlockCropMod("block_crop_nickel");
    public static final Block PLATINIUM_CROP = new BlockCropMod("block_crop_platinium");
    public static final Block SILVERINGOT_CROP = new BlockCropMod("block_crop_silveringot");
    public static final Block STEEL_CROP = new BlockCropMod("block_crop_steel");
    public static final Block TIN_CROP = new BlockCropMod("block_crop_tin");
    public static final Block TITANIUM_CROP = new BlockCropMod("block_crop_titanium");
    public static final Block TUNGSTEN_CROP = new BlockCropMod("block_crop_tungsten");
    public static final Block ZINC_CROP = new BlockCropMod("block_crop_zinc");
    public static final Block MANASTEEL_CROP = new BlockCropMod("block_crop_manasteel");
    public static final Block TERRASTEEL_CROP = new BlockCropMod("block_crop_terrasteel");
    public static final Block MANADIAMOND_CROP = new BlockCropMod("block_crop_manadiamond");
    public static final Block MANAPEARL_CROP = new BlockCropMod("block_crop_manapearl");
    public static final Block ELEMENTIUM_CROP = new BlockCropMod("block_crop_elementium");
    public static final Block DRAGONSTONE_CROP = new BlockCropMod("block_crop_dragonstone");
    public static final Block GEARWOOD_CROP = new BlockCropMod("block_crop_gearwood");
    public static final Block GEARSTONE_CROP = new BlockCropMod("block_crop_gearstone");
    public static final Block GEARIRON_CROP = new BlockCropMod("block_crop_geariron");
    public static final Block GEARGOLD_CROP = new BlockCropMod("block_crop_geargold");
    public static final Block GEARDIAMOND_CROP = new BlockCropMod("block_crop_geardiamond");  
	public static final Block YELLORIUM_CROP = new BlockCropMod("block_crop_yellorium");
	public static final Block BLUTONIUM_CROP = new BlockCropMod("block_crop_blutonium");
	public static final Block CYANITE_CROP = new BlockCropMod("block_crop_cyanite");
	public static final Block GRAPHITE_CROP = new BlockCropMod("block_crop_graphite");
	public static final Block LUDICRITE_CROP = new BlockCropMod("block_crop_ludicrite");
	public static final Block ENDERIUM_CROP = new BlockCropMod("block_crop_enderium");
	public static final Block LUMIUM_CROP = new BlockCropMod("block_crop_lumium");
	public static final Block SIGNALUM_CROP = new BlockCropMod("block_crop_signalum");
	public static final Block CONSTANTAN_CROP = new BlockCropMod("block_crop_constantan");
	public static final Block MITHRIL_CROP = new BlockCropMod("block_crop_mithril");
	public static final Block URANIUM_CROP = new BlockCropMod("block_crop_uranium");
	public static final Block APATITE_CROP = new BlockCropMod("block_crop_apatite");
	public static final Block SILICON_CROP = new BlockCropMod("block_crop_silicon");
	public static final Block DRACONIUM_CROP = new BlockCropMod("block_crop_draconium");
	public static final Block DRACONIUM_AWAKENED_CROP = new BlockCropMod("block_crop_draconium_awakened");
	public static final Block OSMIUM_CROP = new BlockCropMod("block_crop_osmium");
	public static final Block GAIA_CROP = new BlockCropMod("block_crop_gaia");

	public static final Block BLOCK_PLANT_COAL = new BlockPlantMod("block_plant_coal");
	public static final Block BLOCK_PLANT_IRON = new BlockPlantMod("block_plant_iron");
	public static final Block BLOCK_PLANT_GOLD = new BlockPlantMod("block_plant_gold");
	public static final Block BLOCK_PLANT_REDSTONE = new BlockPlantMod("block_plant_redstone");
	public static final Block BLOCK_PLANT_LAPIS = new BlockPlantMod("block_plant_lapis");
	public static final Block BLOCK_PLANT_DIAMOND = new BlockPlantMod("block_plant_diamond");
	public static final Block BLOCK_PLANT_EMERALD = new BlockPlantMod("block_plant_emerald");
	public static final Block BLOCK_PLANT_SPONGE = new BlockPlantMod("block_plant_sponge");
	public static final Block BLOCK_PLANT_GLASS = new BlockPlantMod("block_plant_glass");
	public static final Block BLOCK_PLANT_BRICK = new BlockPlantMod("block_plant_brick");
	public static final Block BLOCK_PLANT_BOOKSHELF = new BlockPlantMod("block_plant_bookshelf");
	public static final Block BLOCK_PLANT_ICE = new BlockPlantMod("block_plant_ice");
	public static final Block BLOCK_PLANT_SNOW = new BlockPlantMod("block_plant_snow");
	public static final Block BLOCK_PLANT_CLAY = new BlockPlantMod("block_plant_clay");
	public static final Block BLOCK_PLANT_SOULSAND = new BlockPlantMod("block_plant_soulsand");
	public static final Block BLOCK_PLANT_GLOWSTONE = new BlockPlantMod("block_plant_glowstone");
	public static final Block BLOCK_PLANT_NETHER = new BlockPlantMod("block_plant_nether");
	public static final Block BLOCK_PLANT_QUARTZ = new BlockPlantMod("block_plant_quartz");
	public static final Block BLOCK_PLANT_SEALANTERN = new BlockPlantMod("block_plant_sealantern");
	public static final Block BLOCK_PLANT_PACKEDICE = new BlockPlantMod("block_plant_packedice");
	public static final Block BLOCK_PLANT_MAGMA = new BlockPlantMod("block_plant_magma");
	public static final Block BLOCK_PLANT_NETHERWART = new BlockPlantMod("block_plant_netherwart");
	public static final Block BLOCK_PLANT_BONE = new BlockPlantMod("block_plant_bone");
	public static final Block BLOCK_PLANT_OBSIDIAN = new BlockPlantMod("block_plant_obsidian");
	public static final Block BLOCK_PLANT_END = new BlockPlantMod("block_plant_end");
	public static final Block BLOCK_PLANT_ELEMENTAL = new BlockPlantMod("block_plant_elemental");
        	 
	public static final Block COAL_STEM = new BlockStemMod(BLOCK_PLANT_COAL, "stem_coal");
	public static final Block IRON_STEM = new BlockStemMod(BLOCK_PLANT_IRON, "stem_iron");
	public static final Block GOLD_STEM = new BlockStemMod(BLOCK_PLANT_GOLD, "stem_gold");
	public static final Block REDSTONE_STEM = new BlockStemMod(BLOCK_PLANT_REDSTONE, "stem_redstone");
	public static final Block LAPIS_STEM = new BlockStemMod(BLOCK_PLANT_LAPIS, "stem_lapis");
	public static final Block DIAMOND_STEM = new BlockStemMod(BLOCK_PLANT_DIAMOND, "stem_diamond");
	public static final Block EMERALD_STEM = new BlockStemMod(BLOCK_PLANT_EMERALD, "stem_emerald");
	public static final Block SPONGE_STEM = new BlockStemMod(BLOCK_PLANT_SPONGE, "stem_sponge");
	public static final Block GLASS_STEM = new BlockStemMod(BLOCK_PLANT_GLASS, "stem_glass");
	public static final Block BRICK_STEM = new BlockStemMod(BLOCK_PLANT_BRICK, "stem_brick");
	public static final Block BOOKSHELF_STEM = new BlockStemMod(BLOCK_PLANT_BOOKSHELF, "stem_bookshelf");
	public static final Block ICE_STEM = new BlockStemMod(BLOCK_PLANT_ICE, "stem_ice");
	public static final Block SNOW_STEM = new BlockStemMod(BLOCK_PLANT_SNOW, "stem_snow");
	public static final Block CLAY_STEM = new BlockStemMod(BLOCK_PLANT_CLAY, "stem_clay");
	public static final Block SOULSAND_STEM = new BlockStemMod(BLOCK_PLANT_SOULSAND, "stem_soulsand");
	public static final Block GLOWSTONE_STEM = new BlockStemMod(BLOCK_PLANT_GLOWSTONE, "stem_glowstone");
	public static final Block NETHER_STEM = new BlockStemMod(BLOCK_PLANT_NETHER, "stem_nether");
	public static final Block QUARTZ_STEM = new BlockStemMod(BLOCK_PLANT_QUARTZ, "stem_quartz");
	public static final Block SEALANTERN_STEM = new BlockStemMod(BLOCK_PLANT_SEALANTERN, "stem_sealantern");
	public static final Block PACKEDICE_STEM = new BlockStemMod(BLOCK_PLANT_PACKEDICE, "stem_packedice");
	public static final Block MAGMA_STEM = new BlockStemMod(BLOCK_PLANT_MAGMA, "stem_magma");
	public static final Block NETHERWART_STEM = new BlockStemMod(BLOCK_PLANT_NETHERWART, "stem_netherwart");
	public static final Block BONE_STEM = new BlockStemMod(BLOCK_PLANT_BONE, "stem_bone");
	public static final Block OBSIDIAN_STEM = new BlockStemMod(BLOCK_PLANT_OBSIDIAN, "stem_obsidian");
	public static final Block END_STEM = new BlockStemMod(BLOCK_PLANT_END, "stem_end");
	public static final Block ELEMENTAL_STEM = new BlockStemMod(BLOCK_PLANT_ELEMENTAL, "stem_elemental");
	
	public static final Block REWARD = new BlockReward();
	public static final Block GREENHOUSE = new BlockGreenhouse();
	public static final Block APRICOT_PLANT = new BlockPlant("apricot_plant");
	public static final Block BANANA_PLANT = new BlockPlant("banana_plant");
	public static final Block CHERRY_PLANT = new BlockPlant("cherry_plant");
	public static final Block KIWI_PLANT = new BlockPlant("kiwi_plant");
	public static final Block LEMON_PLANT = new BlockPlant("lemon_plant");
	public static final Block ORANGE_PLANT = new BlockPlant("orange_plant");
	public static final Block PEAR_PLANT = new BlockPlant("pear_plant");
	public static final Block APRICOT_CROP = new BlockCropMod("apricot_crop");
	public static final Block BANANA_CROP = new BlockCropMod("banana_crop");
	public static final Block CHERRY_CROP = new BlockCropMod("cherry_crop");
	public static final Block KIWI_CROP = new BlockCropMod("kiwi_crop");
	public static final Block LEMON_CROP = new BlockCropMod("lemon_crop");
	public static final Block ORANGE_CROP = new BlockCropMod("orange_crop");
	public static final Block PEAR_CROP = new BlockCropMod("pear_crop");

	public static final Block COAL_FURNACE = new BlockCoalFurnace(false, "coal_furnace");
	public static final Block IRON_FURNACE = new BlockIronFurnace(false, "iron_furnace");
	public static final Block GOLD_FURNACE = new BlockGoldFurnace(false, "gold_furnace");
	public static final Block REDSTONE_FURNACE = new BlockRedstoneFurnace(false, "redstone_furnace");
	public static final Block LAPIS_FURNACE = new BlockLapisFurnace(false, "lapis_furnace");
	public static final Block DIAMOND_FURNACE = new BlockDiamondFurnace(false, "diamond_furnace");
	public static final Block OBSIDIAN_FURNACE = new BlockObsidianFurnace(false, "obsidian_furnace");
	public static final Block RENFORCED_FURNACE = new BlockRenforcedFurnace(false, "renforced_furnace");	
	public static final Block FIRE_FURNACE = new BlockFireFurnace(false, "fire_furnace");
	
	public static final Block LIT_COAL_FURNACE = new BlockCoalFurnace(true, "lit_coal_furnace").setLightLevel(0.875F);
	public static final Block LIT_IRON_FURNACE = new BlockIronFurnace(true, "lit_iron_furnace").setLightLevel(0.875F);
	public static final Block LIT_GOLD_FURNACE = new BlockGoldFurnace(true, "lit_gold_furnace").setLightLevel(0.875F);
	public static final Block LIT_REDSTONE_FURNACE = new BlockRedstoneFurnace(true, "lit_redstone_furnace").setLightLevel(0.875F);
	public static final Block LIT_LAPIS_FURNACE = new BlockLapisFurnace(true, "lit_lapis_furnace").setLightLevel(0.875F);
	public static final Block LIT_DIAMOND_FURNACE = new BlockDiamondFurnace(true, "lit_diamond_furnace").setLightLevel(0.875F);
	public static final Block LIT_OBSIDIAN_FURNACE = new BlockObsidianFurnace(true, "lit_obsidian_furnace").setLightLevel(0.875F);
	public static final Block LIT_RENFORCED_FURNACE = new BlockRenforcedFurnace(true, "lit_renforced_furnace").setLightLevel(0.875F);
	public static final Block LIT_FIRE_FURNACE = new BlockFireFurnace(true, "lit_fire_furnace").setLightLevel(0.875F);

    public static void setBlockName(Block block, String name)
    {
    	block.setRegistryName(Reference.MOD_ID, name).setUnlocalizedName(Reference.MOD_ID + "." + name);
    }

}
