package com.croparia.mod.Init;

import com.croparia.mod.Reference;
import com.croparia.mod.Items.ItemAirArmor;
import com.croparia.mod.Items.ItemCollector;
import com.croparia.mod.Items.ItemEarthArmor;
import com.croparia.mod.Items.ItemFireArmor;
import com.croparia.mod.Items.ItemFruitCompatMod;
import com.croparia.mod.Items.ItemFruitMod;
import com.croparia.mod.Items.ItemGem;
import com.croparia.mod.Items.ItemMod;
import com.croparia.mod.Items.ItemModArmor;
import com.croparia.mod.Items.ItemSeedMod;
import com.croparia.mod.Items.ItemWaterArmor;
import com.croparia.mod.Items.stonehelp;
import com.croparia.mod.Items.ItemBlock.GreenHouseItemBlock;
import com.croparia.mod.Items.Material.ModArmorMaterial;
import com.croparia.mod.Items.Material.ModToolMaterial;
import com.croparia.mod.Items.Relics.ItemHornPlenty;
import com.croparia.mod.Items.Relics.ItemInfiniteApple;
import com.croparia.mod.Items.Relics.ItemMidasHand;
import com.croparia.mod.Items.Tools.ItemAxeMod;
import com.croparia.mod.Items.Tools.ItemElementalHoeMod;
import com.croparia.mod.Items.Tools.ItemElementalMultitool;
import com.croparia.mod.Items.Tools.ItemHoeMod;
import com.croparia.mod.Items.Tools.ItemMultitool;
import com.croparia.mod.Items.Tools.ItemPickaxeMod;
import com.croparia.mod.Items.Tools.ItemRake;
import com.croparia.mod.Items.Tools.ItemShovelMod;
import com.croparia.mod.Items.Tools.ItemSwordMod;

import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.init.Blocks;
import net.minecraft.inventory.EntityEquipmentSlot;
import net.minecraft.item.Item;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraft.item.ItemBlock;
import net.minecraft.item.ItemFood;
import net.minecraft.item.ItemSeedFood;
import net.minecraftforge.client.event.ModelRegistryEvent;
import net.minecraftforge.client.model.ModelLoader;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

@EventBusSubscriber(value = Side.CLIENT, modid = Reference.MOD_ID)
public class ModItems
{
	//public static final Item COAL_SEED = new stonehelp().setRegistryName(Reference.MOD_ID, "seed_crop_coal").setUnlocalizedName(Reference.MOD_ID + "." + "seed_crop_coal").setCreativeTab(Reference.TAB);
	public static final Item COAL_SEED = new ItemSeedMod(ModBlocks.COAL_CROP, Blocks.FARMLAND, "seed_crop_coal");
	public static final Item IRON_SEED = new ItemSeedMod(ModBlocks.IRON_CROP, Blocks.FARMLAND, "seed_crop_iron");
	public static final Item GOLD_SEED = new ItemSeedMod(ModBlocks.GOLD_CROP, Blocks.FARMLAND, "seed_crop_gold");
	public static final Item REDSTONE_SEED = new ItemSeedMod(ModBlocks.REDSTONE_CROP, Blocks.FARMLAND, "seed_crop_redstone");
	public static final Item LAPIS_SEED = new ItemSeedMod(ModBlocks.LAPIS_CROP, Blocks.FARMLAND, "seed_crop_lapis");
	public static final Item DIAMOND_SEED = new ItemSeedMod(ModBlocks.DIAMOND_CROP, Blocks.FARMLAND, "seed_crop_diamond");
	public static final Item EMERALD_SEED = new ItemSeedMod(ModBlocks.EMERALD_CROP, Blocks.FARMLAND, "seed_crop_emerald");
	public static final Item ELEMENTAL_SEED = new ItemSeedMod(ModBlocks.ELEMENTAL_CROP, Blocks.FARMLAND, "seed_crop_elemental");
	public static final Item CLAY_SEED = new ItemSeedMod(ModBlocks.CLAY_CROP, Blocks.FARMLAND, "seed_crop_clay");
	public static final Item GLOWSTONE_SEED = new ItemSeedMod(ModBlocks.GLOWSTONE_CROP, Blocks.FARMLAND, "seed_crop_glowstone");
	public static final Item QUARTZ_SEED = new ItemSeedMod(ModBlocks.QUARTZ_CROP, Blocks.FARMLAND, "seed_crop_quartz");
	public static final Item SHARD_SEED = new ItemSeedMod(ModBlocks.SHARD_CROP, Blocks.FARMLAND, "seed_crop_shard");
	public static final Item CRYSTAL_SEED = new ItemSeedMod(ModBlocks.CRYSTAL_CROP, Blocks.FARMLAND, "seed_crop_crystal");
	public static final Item PAPER_SEED = new ItemSeedMod(ModBlocks.PAPER_CROP, Blocks.FARMLAND, "seed_crop_paper");
	public static final Item SUGAR_SEED = new ItemSeedMod(ModBlocks.SUGAR_CROP, Blocks.FARMLAND, "seed_crop_sugar");
	public static final Item CHARCOAL_SEED = new ItemSeedMod(ModBlocks.CHARCOAL_CROP, Blocks.FARMLAND, "seed_crop_charcoal");
	public static final Item FLINT_SEED = new ItemSeedMod(ModBlocks.FLINT_CROP, Blocks.FARMLAND, "seed_crop_flint");
	public static final Item SNOWBALL_SEED = new ItemSeedMod(ModBlocks.SNOWBALL_CROP, Blocks.FARMLAND, "seed_crop_snowball");
	public static final Item FIREWORK_SEED = new ItemSeedMod(ModBlocks.FIREWORK_CROP, Blocks.FARMLAND, "seed_crop_firework");
	public static final Item NETHER_SEED = new ItemSeedMod(ModBlocks.NETHER_CROP, Blocks.FARMLAND, "seed_crop_nether");
	public static final Item BOTTLE_SEED = new ItemSeedMod(ModBlocks.BOTTLE_CROP, Blocks.FARMLAND, "seed_crop_bottle");
	public static final Item TOTEM_SEED = new ItemSeedMod(ModBlocks.TOTEM_CROP, Blocks.FARMLAND, "seed_crop_totem");
	public static final Item LEAD2_SEED = new ItemSeedMod(ModBlocks.LEAD2_CROP, Blocks.FARMLAND, "seed_crop_lead2");
	public static final Item NAMETAG_SEED = new ItemSeedMod(ModBlocks.NAMETAG_CROP, Blocks.FARMLAND, "seed_crop_nametag");
	public static final Item XP_SEED = new ItemSeedMod(ModBlocks.XP_CROP, Blocks.FARMLAND, "seed_crop_xp");
	public static final Item ENDER_SEED = new ItemSeedMod(ModBlocks.ENDER_CROP, Blocks.FARMLAND, "seed_crop_ender");
	public static final Item BONE_SEED = new ItemSeedMod(ModBlocks.BONE_CROP, Blocks.FARMLAND, "seed_crop_bone");
	public static final Item EYE_SEED = new ItemSeedMod(ModBlocks.EYE_CROP, Blocks.FARMLAND, "seed_crop_eye");
	public static final Item POWDER_SEED = new ItemSeedMod(ModBlocks.POWDER_CROP, Blocks.FARMLAND, "seed_crop_powder");
	public static final Item BLAZE_SEED = new ItemSeedMod(ModBlocks.BLAZE_CROP, Blocks.FARMLAND, "seed_crop_blaze");
	public static final Item GHAST_SEED = new ItemSeedMod(ModBlocks.GHAST_CROP, Blocks.FARMLAND, "seed_crop_ghast");
	public static final Item MAGMA_SEED = new ItemSeedMod(ModBlocks.MAGMA_CROP, Blocks.FARMLAND, "seed_crop_magma");
	public static final Item SHELL_SEED = new ItemSeedMod(ModBlocks.SHELL_CROP, Blocks.FARMLAND, "seed_crop_shell");
	public static final Item SLIME_SEED = new ItemSeedMod(ModBlocks.SLIME_CROP, Blocks.FARMLAND, "seed_crop_slime");
	public static final Item STAR_SEED = new ItemSeedMod(ModBlocks.STAR_CROP, Blocks.FARMLAND, "seed_crop_star");
	public static final Item STRING_SEED = new ItemSeedMod(ModBlocks.STRING_CROP, Blocks.FARMLAND, "seed_crop_string");
	public static final Item ZOMBIE_SEED = new ItemSeedMod(ModBlocks.ZOMBIE_CROP, Blocks.FARMLAND, "seed_crop_zombie");	
	public static final Item APPLE_SEED = new ItemSeedMod(ModBlocks.APPLE_CROP, Blocks.FARMLAND, "seed_crop_apple");
	public static final Item GOLDENAPPLE_SEED = new ItemSeedMod(ModBlocks.GOLDENAPPLE_CROP, Blocks.FARMLAND, "seed_crop_goldenapple");
	public static final Item BREAD_SEED = new ItemSeedMod(ModBlocks.BREAD_CROP, Blocks.FARMLAND, "seed_crop_bread");
	public static final Item EGG_SEED = new ItemSeedMod(ModBlocks.EGG_CROP, Blocks.FARMLAND, "seed_crop_egg");
	public static final Item CLOWNFISH_SEED = new ItemSeedMod(ModBlocks.CLOWNFISH_CROP, Blocks.FARMLAND, "seed_crop_clownfish");
	public static final Item PUFFERFISH_SEED = new ItemSeedMod(ModBlocks.PUFFERFISH_CROP, Blocks.FARMLAND, "seed_crop_pufferfish");
	public static final Item COOKIE_SEED = new ItemSeedMod(ModBlocks.COOKIE_CROP, Blocks.FARMLAND, "seed_crop_cookie");
	public static final Item CHORUS_SEED = new ItemSeedMod(ModBlocks.CHORUS_CROP, Blocks.FARMLAND, "seed_crop_chorus");
	public static final Item RAWPORC_SEED = new ItemSeedMod(ModBlocks.RAWPORC_CROP, Blocks.FARMLAND, "seed_crop_rawporc");
	public static final Item RAWBEEF_SEED = new ItemSeedMod(ModBlocks.RAWBEEF_CROP, Blocks.FARMLAND, "seed_crop_rawbeef");
	public static final Item FISH_SEED = new ItemSeedMod(ModBlocks.FISH_CROP, Blocks.FARMLAND, "seed_crop_fish");
	public static final Item SALMON_SEED = new ItemSeedMod(ModBlocks.SALMON_CROP, Blocks.FARMLAND, "seed_crop_salmon");
	public static final Item RAWCHICKEN_SEED = new ItemSeedMod(ModBlocks.RAWCHICKEN_CROP, Blocks.FARMLAND, "seed_crop_rawchicken");
	public static final Item RAWRABBIT_SEED = new ItemSeedMod(ModBlocks.RAWRABBIT_CROP, Blocks.FARMLAND, "seed_crop_rawrabbit");
	public static final Item RAWMUTTON_SEED = new ItemSeedMod(ModBlocks.RAWMUTTON_CROP, Blocks.FARMLAND, "seed_crop_rawmutton");
	public static final Item ORANGE_SEED = new ItemSeedMod(ModBlocks.ORANGE_CROP1, Blocks.FARMLAND, "seed_crop_orange"); 
	public static final Item MAGENTA_SEED = new ItemSeedMod(ModBlocks.MAGENTA_CROP, Blocks.FARMLAND, "seed_crop_magenta");
	public static final Item LIGHTBLUE_SEED = new ItemSeedMod(ModBlocks.LIGHTBLUE_CROP, Blocks.FARMLAND, "seed_crop_lightblue");
	public static final Item YELLOW_SEED = new ItemSeedMod(ModBlocks.YELLOW_CROP, Blocks.FARMLAND, "seed_crop_yellow");
	public static final Item LIME_SEED = new ItemSeedMod(ModBlocks.LIME_CROP, Blocks.FARMLAND, "seed_crop_lime");
	public static final Item PINK_SEED = new ItemSeedMod(ModBlocks.PINK_CROP, Blocks.FARMLAND, "seed_crop_pink");
	public static final Item GRAY_SEED = new ItemSeedMod(ModBlocks.GRAY_CROP, Blocks.FARMLAND, "seed_crop_gray");
	public static final Item SILVER_SEED = new ItemSeedMod(ModBlocks.SILVER_CROP, Blocks.FARMLAND, "seed_crop_silver");
	public static final Item CYAN_SEED = new ItemSeedMod(ModBlocks.CYAN_CROP, Blocks.FARMLAND, "seed_crop_cyan");
	public static final Item PURPLE_SEED = new ItemSeedMod(ModBlocks.PURPLE_CROP, Blocks.FARMLAND, "seed_crop_purple");
	public static final Item BROWN_SEED = new ItemSeedMod(ModBlocks.BROWN_CROP, Blocks.FARMLAND, "seed_crop_brown");
	public static final Item GREEN_SEED = new ItemSeedMod(ModBlocks.GREEN_CROP, Blocks.FARMLAND, "seed_crop_green");
	public static final Item RED_SEED = new ItemSeedMod(ModBlocks.RED_CROP, Blocks.FARMLAND, "seed_crop_red");
	public static final Item BLACK_SEED = new ItemSeedMod(ModBlocks.BLACK_CROP, Blocks.FARMLAND, "seed_crop_black");		
	public static final Item VINE_SEED = new ItemSeedMod(ModBlocks.VINE_CROP, Blocks.FARMLAND, "seed_crop_vine");
	public static final Item LILYPAD_SEED = new ItemSeedMod(ModBlocks.LILYPAD_CROP, Blocks.FARMLAND, "seed_crop_lilypad");
	public static final Item TALLGRASS_SEED = new ItemSeedMod(ModBlocks.TALLGRASS_CROP, Blocks.FARMLAND, "seed_crop_tallgrass");
	public static final Item LARGEFERN_SEED = new ItemSeedMod(ModBlocks.LARGEFERN_CROP, Blocks.FARMLAND, "seed_crop_largefern");
	public static final Item BUSH_SEED = new ItemSeedMod(ModBlocks.BUSH_CROP, Blocks.FARMLAND, "seed_crop_bush");
	public static final Item GRASS1_SEED = new ItemSeedMod(ModBlocks.GRASS1_CROP, Blocks.FARMLAND, "seed_crop_grass1");
	public static final Item FERN_SEED = new ItemSeedMod(ModBlocks.FERN_CROP, Blocks.FARMLAND, "seed_crop_fern");
	public static final Item OAK_SEED = new ItemSeedMod(ModBlocks.OAK_CROP, Blocks.FARMLAND, "seed_crop_oak");
	public static final Item BIRCH_SEED = new ItemSeedMod(ModBlocks.BIRCH_CROP, Blocks.FARMLAND, "seed_crop_birch");
	public static final Item SPRUCE_SEED = new ItemSeedMod(ModBlocks.SPRUCE_CROP, Blocks.FARMLAND, "seed_crop_spruce");
	public static final Item JUNGLE_SEED = new ItemSeedMod(ModBlocks.JUNGLE_CROP, Blocks.FARMLAND, "seed_crop_jungle");
	public static final Item DARKOAK_SEED = new ItemSeedMod(ModBlocks.DARKOAK_CROP, Blocks.FARMLAND, "seed_crop_darkoak");
	public static final Item ACACIA_SEED = new ItemSeedMod(ModBlocks.ACACIA_CROP, Blocks.FARMLAND, "seed_crop_acacia");
	public static final Item LEATHER_SEED = new ItemSeedMod(ModBlocks.LEATHER_CROP, Blocks.FARMLAND, "seed_crop_leather");
	public static final Item FEATHER_SEED = new ItemSeedMod(ModBlocks.FEATHER_CROP, Blocks.FARMLAND, "seed_crop_feather");
	public static final Item FOOT_SEED = new ItemSeedMod(ModBlocks.FOOT_CROP, Blocks.FARMLAND, "seed_crop_foot");
	public static final Item HIDE_SEED = new ItemSeedMod(ModBlocks.HIDE_CROP, Blocks.FARMLAND, "seed_crop_hide");
	   
	public static final Item ALUMINIUM_SEED = new ItemSeedMod(ModBlocks.ALUMINIUM_CROP, Blocks.FARMLAND, "seed_crop_aluminium");
    public static final Item BRASS_SEED = new ItemSeedMod(ModBlocks.BRASS_CROP, Blocks.FARMLAND, "seed_crop_brass");
    public static final Item BRONZE_SEED = new ItemSeedMod(ModBlocks.BRONZE_CROP, Blocks.FARMLAND, "seed_crop_bronze");
    public static final Item CHROME_SEED = new ItemSeedMod(ModBlocks.CHROME_CROP, Blocks.FARMLAND, "seed_crop_chrome");
    public static final Item COPPER_SEED = new ItemSeedMod(ModBlocks.COPPER_CROP, Blocks.FARMLAND, "seed_crop_copper");
    public static final Item ELECTRUM_SEED = new ItemSeedMod(ModBlocks.ELECTRUM_CROP, Blocks.FARMLAND, "seed_crop_electrum");
    public static final Item INVAR_SEED = new ItemSeedMod(ModBlocks.INVAR_CROP, Blocks.FARMLAND, "seed_crop_invar");
    public static final Item IRIDIUM_SEED = new ItemSeedMod(ModBlocks.IRIDIUM_CROP, Blocks.FARMLAND, "seed_crop_iridium");
    public static final Item LEAD_SEED = new ItemSeedMod(ModBlocks.LEAD_CROP, Blocks.FARMLAND, "seed_crop_lead");
    public static final Item NICKEL_SEED = new ItemSeedMod(ModBlocks.NICKEL_CROP, Blocks.FARMLAND, "seed_crop_nickel");
    public static final Item PLATINIUM_SEED = new ItemSeedMod(ModBlocks.PLATINIUM_CROP, Blocks.FARMLAND, "seed_crop_platinium");
    public static final Item SILVERINGOT_SEED = new ItemSeedMod(ModBlocks.SILVERINGOT_CROP, Blocks.FARMLAND, "seed_crop_silveringot");
    public static final Item STEEL_SEED = new ItemSeedMod(ModBlocks.STEEL_CROP, Blocks.FARMLAND, "seed_crop_steel");
    public static final Item TIN_SEED = new ItemSeedMod(ModBlocks.TIN_CROP, Blocks.FARMLAND, "seed_crop_tin");
    public static final Item TITANIUM_SEED = new ItemSeedMod(ModBlocks.TITANIUM_CROP, Blocks.FARMLAND, "seed_crop_titanium");
    public static final Item TUNGSTEN_SEED = new ItemSeedMod(ModBlocks.TUNGSTEN_CROP, Blocks.FARMLAND, "seed_crop_tungsten");
    public static final Item ZINC_SEED = new ItemSeedMod(ModBlocks.ZINC_CROP, Blocks.FARMLAND, "seed_crop_zinc");
    public static final Item MANASTEEL_SEED = new ItemSeedMod(ModBlocks.MANASTEEL_CROP, Blocks.FARMLAND, "seed_crop_manasteel");
    public static final Item TERRASTEEL_SEED = new ItemSeedMod(ModBlocks.TERRASTEEL_CROP, Blocks.FARMLAND, "seed_crop_terrasteel");
    public static final Item MANADIAMOND_SEED = new ItemSeedMod(ModBlocks.MANADIAMOND_CROP, Blocks.FARMLAND, "seed_crop_manadiamond");
    public static final Item MANAPEARL_SEED = new ItemSeedMod(ModBlocks.MANAPEARL_CROP, Blocks.FARMLAND, "seed_crop_manapearl");
    public static final Item ELEMENTIUM_SEED = new ItemSeedMod(ModBlocks.ELEMENTIUM_CROP, Blocks.FARMLAND, "seed_crop_elementium");
    public static final Item DRAGONSTONE_SEED = new ItemSeedMod(ModBlocks.DRAGONSTONE_CROP, Blocks.FARMLAND, "seed_crop_dragonstone");
    public static final Item GEARWOOD_SEED = new ItemSeedMod(ModBlocks.GEARWOOD_CROP, Blocks.FARMLAND, "seed_crop_gearwood");
    public static final Item GEARSTONE_SEED = new ItemSeedMod(ModBlocks.GEARSTONE_CROP, Blocks.FARMLAND, "seed_crop_gearstone");
    public static final Item GEARIRON_SEED = new ItemSeedMod(ModBlocks.GEARIRON_CROP, Blocks.FARMLAND, "seed_crop_geariron");
    public static final Item GEARGOLD_SEED = new ItemSeedMod(ModBlocks.GEARGOLD_CROP, Blocks.FARMLAND, "seed_crop_geargold");
    public static final Item GEARDIAMOND_SEED = new ItemSeedMod(ModBlocks.GEARDIAMOND_CROP, Blocks.FARMLAND, "seed_crop_geardiamond");   
	public static final Item YELLORIUM_SEED = new ItemSeedMod(ModBlocks.YELLORIUM_CROP, Blocks.FARMLAND, "seed_crop_yellorium");
	public static final Item BLUTONIUM_SEED = new ItemSeedMod(ModBlocks.BLUTONIUM_CROP, Blocks.FARMLAND, "seed_crop_blutonium");
	public static final Item CYANITE_SEED = new ItemSeedMod(ModBlocks.CYANITE_CROP, Blocks.FARMLAND, "seed_crop_cyanite");
	public static final Item GRAPHITE_SEED = new ItemSeedMod(ModBlocks.GRAPHITE_CROP, Blocks.FARMLAND, "seed_crop_graphite");
	public static final Item LUDICRITE_SEED = new ItemSeedMod(ModBlocks.LUDICRITE_CROP, Blocks.FARMLAND, "seed_crop_ludicrite");
	public static final Item ENDERIUM_SEED = new ItemSeedMod(ModBlocks.ENDERIUM_CROP, Blocks.FARMLAND, "seed_crop_enderium");
	public static final Item LUMIUM_SEED = new ItemSeedMod(ModBlocks.LUMIUM_CROP, Blocks.FARMLAND, "seed_crop_lumium");
	public static final Item SIGNALUM_SEED = new ItemSeedMod(ModBlocks.SIGNALUM_CROP, Blocks.FARMLAND, "seed_crop_signalum");
	public static final Item CONSTANTAN_SEED = new ItemSeedMod(ModBlocks.CONSTANTAN_CROP, Blocks.FARMLAND, "seed_crop_constantan");
	public static final Item MITHRIL_SEED = new ItemSeedMod(ModBlocks.MITHRIL_CROP, Blocks.FARMLAND, "seed_crop_mithril");
	public static final Item URANIUM_SEED = new ItemSeedMod(ModBlocks.URANIUM_CROP, Blocks.FARMLAND, "seed_crop_uranium");
	public static final Item APATITE_SEED = new ItemSeedMod(ModBlocks.APATITE_CROP, Blocks.FARMLAND, "seed_crop_apatite");
	public static final Item SILICON_SEED = new ItemSeedMod(ModBlocks.SILICON_CROP, Blocks.FARMLAND, "seed_crop_silicon");
	public static final Item DRACONIUM_SEED = new ItemSeedMod(ModBlocks.DRACONIUM_CROP, Blocks.FARMLAND, "seed_crop_draconium");
	public static final Item DRACONIUM_AWAKENED_SEED = new ItemSeedMod(ModBlocks.DRACONIUM_AWAKENED_CROP, Blocks.FARMLAND, "seed_crop_draconium_awakened");
	public static final Item OSMIUM_SEED = new ItemSeedMod(ModBlocks.OSMIUM_CROP, Blocks.FARMLAND, "seed_crop_osmium");
	public static final Item GAIA_SEED = new ItemSeedMod(ModBlocks.GAIA_CROP, Blocks.FARMLAND, "seed_crop_gaia");

	public static final Item COAL_SEED_STEM = new ItemSeedMod(ModBlocks.COAL_STEM, Blocks.FARMLAND, "seed_stem_coal");
	public static final Item IRON_SEED_STEM = new ItemSeedMod(ModBlocks.IRON_STEM, Blocks.FARMLAND, "seed_stem_iron");
	public static final Item GOLD_SEED_STEM = new ItemSeedMod(ModBlocks.GOLD_STEM, Blocks.FARMLAND, "seed_stem_gold");
	public static final Item REDSTONE_SEED_STEM = new ItemSeedMod(ModBlocks.REDSTONE_STEM, Blocks.FARMLAND, "seed_stem_redstone");
	public static final Item LAPIS_SEED_STEM = new ItemSeedMod(ModBlocks.LAPIS_STEM, Blocks.FARMLAND, "seed_stem_lapis");
	public static final Item DIAMOND_SEED_STEM = new ItemSeedMod(ModBlocks.DIAMOND_STEM, Blocks.FARMLAND, "seed_stem_diamond");
	public static final Item EMERALD_SEED_STEM = new ItemSeedMod(ModBlocks.EMERALD_STEM, Blocks.FARMLAND, "seed_stem_emerald");
	public static final Item SPONGE_SEED_STEM = new ItemSeedMod(ModBlocks.SPONGE_STEM, Blocks.FARMLAND, "seed_stem_sponge");
	public static final Item GLASS_SEED_STEM = new ItemSeedMod(ModBlocks.GLASS_STEM, Blocks.FARMLAND, "seed_stem_glass");
	public static final Item BRICK_SEED_STEM = new ItemSeedMod(ModBlocks.BRICK_STEM, Blocks.FARMLAND, "seed_stem_brick");
	public static final Item BOOKSHELF_SEED_STEM = new ItemSeedMod(ModBlocks.BOOKSHELF_STEM, Blocks.FARMLAND, "seed_stem_bookshelf");
	public static final Item ICE_SEED_STEM = new ItemSeedMod(ModBlocks.ICE_STEM, Blocks.FARMLAND, "seed_stem_ice");
	public static final Item SNOW_SEED_STEM = new ItemSeedMod(ModBlocks.SNOW_STEM, Blocks.FARMLAND, "seed_stem_snow");
	public static final Item CLAY_SEED_STEM = new ItemSeedMod(ModBlocks.CLAY_STEM, Blocks.FARMLAND, "seed_stem_clay");
	public static final Item SOULSAND_SEED_STEM = new ItemSeedMod(ModBlocks.SOULSAND_STEM, Blocks.FARMLAND, "seed_stem_soulsand");
	public static final Item GLOWSTONE_SEED_STEM = new ItemSeedMod(ModBlocks.GLOWSTONE_STEM, Blocks.FARMLAND, "seed_stem_glowstone");
	public static final Item NETHER_SEED_STEM = new ItemSeedMod(ModBlocks.NETHER_STEM, Blocks.FARMLAND, "seed_stem_nether");
	public static final Item QUARTZ_SEED_STEM = new ItemSeedMod(ModBlocks.QUARTZ_STEM, Blocks.FARMLAND, "seed_stem_quartz");
	public static final Item SEALANTERN_SEED_STEM = new ItemSeedMod(ModBlocks.SEALANTERN_STEM, Blocks.FARMLAND, "seed_stem_sealantern");
	public static final Item PACKEDICE_SEED_STEM = new ItemSeedMod(ModBlocks.PACKEDICE_STEM, Blocks.FARMLAND, "seed_stem_packedice");
	public static final Item MAGMA_SEED_STEM = new ItemSeedMod(ModBlocks.MAGMA_STEM, Blocks.FARMLAND, "seed_stem_magma");
	public static final Item NETHERWART_SEED_STEM = new ItemSeedMod(ModBlocks.NETHERWART_STEM, Blocks.FARMLAND, "seed_stem_netherwart");
	public static final Item BONE_SEED_STEM = new ItemSeedMod(ModBlocks.BONE_STEM, Blocks.FARMLAND, "seed_stem_bone");
	public static final Item OBSIDIAN_SEED_STEM = new ItemSeedMod(ModBlocks.OBSIDIAN_STEM, Blocks.FARMLAND, "seed_stem_obsidian");
	public static final Item END_SEED_STEM = new ItemSeedMod(ModBlocks.END_STEM, Blocks.FARMLAND, "seed_stem_end");
	public static final Item ELEMENTAL_SEED_STEM = new ItemSeedMod(ModBlocks.ELEMENTAL_STEM, Blocks.FARMLAND, "seed_stem_elemental");
	
	public static final Item COAL_FRUIT = new ItemFruitMod("fruit_coal");
	public static final Item IRON_FRUIT = new ItemFruitMod("fruit_iron");
	public static final Item GOLD_FRUIT = new ItemFruitMod("fruit_gold");
	public static final Item REDSTONE_FRUIT = new ItemFruitMod("fruit_redstone");
	public static final Item LAPIS_FRUIT = new ItemFruitMod("fruit_lapis");
	public static final Item DIAMOND_FRUIT = new ItemFruitMod("fruit_diamond");
	public static final Item EMERALD_FRUIT = new ItemFruitMod("fruit_emerald");
	public static final Item ELEMENTAL_FRUIT = new ItemFruitMod("fruit_elemental");
	public static final Item CLAY_FRUIT = new ItemFruitMod("fruit_clay");
	public static final Item GLOWSTONE_FRUIT = new ItemFruitMod("fruit_glowstone");
	public static final Item QUARTZ_FRUIT = new ItemFruitMod("fruit_quartz");
	public static final Item SHARD_FRUIT = new ItemFruitMod("fruit_shard");
	public static final Item CRYSTAL_FRUIT = new ItemFruitMod("fruit_crystal");
	public static final Item PAPER_FRUIT = new ItemFruitMod("fruit_paper");
	public static final Item SUGAR_FRUIT = new ItemFruitMod("fruit_sugar");
	public static final Item CHARCOAL_FRUIT = new ItemFruitMod("fruit_charcoal");
	public static final Item FLINT_FRUIT = new ItemFruitMod("fruit_flint");
	public static final Item SNOWBALL_FRUIT = new ItemFruitMod("fruit_snowball");
	public static final Item FIREWORK_FRUIT = new ItemFruitMod("fruit_firework");
	public static final Item NETHER_FRUIT = new ItemFruitMod("fruit_nether");
	public static final Item BOTTLE_FRUIT = new ItemFruitMod("fruit_bottle");
	public static final Item TOTEM_FRUIT = new ItemFruitMod("fruit_totem");
	public static final Item LEAD2_FRUIT = new ItemFruitMod("fruit_lead2");
	public static final Item NAMETAG_FRUIT = new ItemFruitMod("fruit_nametag");
	public static final Item XP_FRUIT = new ItemFruitMod("fruit_xp");	
	public static final Item ENDER_FRUIT = new ItemFruitMod("fruit_ender");
	public static final Item BONE_FRUIT = new ItemFruitMod("fruit_bone");
	public static final Item EYE_FRUIT = new ItemFruitMod("fruit_eye");
	public static final Item POWDER_FRUIT = new ItemFruitMod("fruit_powder");
	public static final Item BLAZE_FRUIT = new ItemFruitMod("fruit_blaze");
	public static final Item GHAST_FRUIT = new ItemFruitMod("fruit_ghast");
	public static final Item MAGMA_FRUIT = new ItemFruitMod("fruit_magma");
	public static final Item SHELL_FRUIT = new ItemFruitMod("fruit_shell");
	public static final Item SLIME_FRUIT = new ItemFruitMod("fruit_slime");
	public static final Item STAR_FRUIT = new ItemFruitMod("fruit_star");
	public static final Item STRING_FRUIT = new ItemFruitMod("fruit_string");
	public static final Item ZOMBIE_FRUIT = new ItemFruitMod("fruit_zombie");	
	public static final Item APPLE_FRUIT = new ItemFruitMod("fruit_apple");
	public static final Item GOLDENAPPLE_FRUIT = new ItemFruitMod("fruit_gapple");
	public static final Item BREAD_FRUIT = new ItemFruitMod("fruit_bread");
	public static final Item EGG_FRUIT = new ItemFruitMod("fruit_egg");
	public static final Item CLOWNFISH_FRUIT = new ItemFruitMod("fruit_clownfish");
	public static final Item PUFFERFISH_FRUIT = new ItemFruitMod("fruit_pufferfish");
	public static final Item COOKIE_FRUIT = new ItemFruitMod("fruit_cookie");
	public static final Item CHORUS_FRUIT = new ItemFruitMod("fruit_chorus");
	public static final Item RAWPORC_FRUIT = new ItemFruitMod("fruit_rawporc");
	public static final Item RAWBEEF_FRUIT = new ItemFruitMod("fruit_rawbeef");
	public static final Item FISH_FRUIT = new ItemFruitMod("fruit_fish");
	public static final Item SALMON_FRUIT = new ItemFruitMod("fruit_salmon");
	public static final Item RAWCHICKEN_FRUIT = new ItemFruitMod("fruit_rawchicken");
	public static final Item RAWRABBIT_FRUIT = new ItemFruitMod("fruit_rawrabbit");
	public static final Item RAWMUTTON_FRUIT = new ItemFruitMod("fruit_rawmutton");
	public static final Item ORANGE_FRUIT = new ItemFruitMod("fruit_orange"); 
	public static final Item MAGENTA_FRUIT = new ItemFruitMod("fruit_magenta");
	public static final Item LIGHTBLUE_FRUIT = new ItemFruitMod("fruit_lightblue");
	public static final Item YELLOW_FRUIT = new ItemFruitMod("fruit_yellow");
	public static final Item LIME_FRUIT = new ItemFruitMod("fruit_lime");
	public static final Item PINK_FRUIT = new ItemFruitMod("fruit_pink");
	public static final Item GRAY_FRUIT = new ItemFruitMod("fruit_gray");
	public static final Item SILVER_FRUIT = new ItemFruitMod("fruit_silver");
	public static final Item CYAN_FRUIT = new ItemFruitMod("fruit_cyan");
	public static final Item PURPLE_FRUIT = new ItemFruitMod("fruit_purple");
	public static final Item BROWN_FRUIT = new ItemFruitMod("fruit_brown");
	public static final Item GREEN_FRUIT = new ItemFruitMod("fruit_green");
	public static final Item RED_FRUIT = new ItemFruitMod("fruit_red");
	public static final Item BLACK_FRUIT = new ItemFruitMod("fruit_black");		
	public static final Item VINE_FRUIT = new ItemFruitMod("fruit_vine");
	public static final Item LILYPAD_FRUIT = new ItemFruitMod("fruit_lilypad");
	public static final Item TALLGRASS_FRUIT = new ItemFruitMod("fruit_tallgrass");
	public static final Item LARGEFERN_FRUIT = new ItemFruitMod("fruit_largefern");
	public static final Item BUSH_FRUIT = new ItemFruitMod("fruit_bush");
	public static final Item GRASS1_FRUIT = new ItemFruitMod("fruit_grass1");
	public static final Item FERN_FRUIT = new ItemFruitMod("fruit_fern");
	public static final Item OAK_FRUIT = new ItemFruitMod("fruit_oak");
	public static final Item BIRCH_FRUIT = new ItemFruitMod("fruit_birch");
	public static final Item SPRUCE_FRUIT = new ItemFruitMod("fruit_spruce");
	public static final Item JUNGLE_FRUIT = new ItemFruitMod("fruit_jungle");
	public static final Item DARKOAK_FRUIT = new ItemFruitMod("fruit_darkoak");
	public static final Item ACACIA_FRUIT = new ItemFruitMod("fruit_acacia");
	public static final Item LEATHER_FRUIT = new ItemFruitMod("fruit_leather");
	public static final Item FEATHER_FRUIT = new ItemFruitMod("fruit_feather");
	public static final Item FOOT_FRUIT = new ItemFruitMod("fruit_foot");
	public static final Item HIDE_FRUIT = new ItemFruitMod("fruit_hide");
	
	public static final Item ALUMINIUM_FRUIT = new ItemFruitCompatMod("fruit_aluminium");
    public static final Item BRASS_FRUIT = new ItemFruitCompatMod("fruit_brass");
    public static final Item BRONZE_FRUIT = new ItemFruitCompatMod("fruit_bronze");
    public static final Item CHROME_FRUIT = new ItemFruitCompatMod("fruit_chrome");
    public static final Item COPPER_FRUIT = new ItemFruitCompatMod("fruit_copper");
    public static final Item ELECTRUM_FRUIT = new ItemFruitCompatMod("fruit_electrum");
    public static final Item INVAR_FRUIT = new ItemFruitCompatMod("fruit_invar");
    public static final Item IRIDIUM_FRUIT = new ItemFruitCompatMod("fruit_iridium");
    public static final Item LEAD_FRUIT = new ItemFruitCompatMod("fruit_lead");
    public static final Item NICKEL_FRUIT = new ItemFruitCompatMod("fruit_nickel");
    public static final Item PLATINIUM_FRUIT = new ItemFruitCompatMod("fruit_platinium");
    public static final Item SILVERINGOT_FRUIT = new ItemFruitCompatMod("fruit_silveringot");
    public static final Item STEEL_FRUIT = new ItemFruitCompatMod("fruit_steel");
    public static final Item TIN_FRUIT = new ItemFruitCompatMod("fruit_tin");
    public static final Item TITANIUM_FRUIT = new ItemFruitCompatMod("fruit_titanium");
    public static final Item TUNGSTEN_FRUIT = new ItemFruitCompatMod("fruit_tungsten");
    public static final Item ZINC_FRUIT = new ItemFruitCompatMod("fruit_zinc");
    public static final Item MANASTEEL_FRUIT = new ItemFruitCompatMod("fruit_manasteel");
    public static final Item TERRASTEEL_FRUIT = new ItemFruitCompatMod("fruit_terrasteel");
    public static final Item MANADIAMOND_FRUIT = new ItemFruitCompatMod("fruit_manadiamond");
    public static final Item MANAPEARL_FRUIT = new ItemFruitCompatMod("fruit_manapearl");
    public static final Item ELEMENTIUM_FRUIT = new ItemFruitCompatMod("fruit_elementium");
    public static final Item DRAGONSTONE_FRUIT = new ItemFruitCompatMod("fruit_dragonstone");
    public static final Item GEARWOOD_FRUIT = new ItemFruitCompatMod("fruit_gearwood");
    public static final Item GEARSTONE_FRUIT = new ItemFruitCompatMod("fruit_gearstone");
    public static final Item GEARIRON_FRUIT = new ItemFruitCompatMod("fruit_geariron");
    public static final Item GEARGOLD_FRUIT = new ItemFruitCompatMod("fruit_geargold");
    public static final Item GEARDIAMOND_FRUIT = new ItemFruitCompatMod("fruit_geardiamond");   
	public static final Item YELLORIUM_FRUIT = new ItemFruitCompatMod("fruit_yellorium");
	public static final Item BLUTONIUM_FRUIT = new ItemFruitCompatMod("fruit_blutonium");
	public static final Item CYANITE_FRUIT = new ItemFruitCompatMod("fruit_cyanite");
	public static final Item GRAPHITE_FRUIT = new ItemFruitCompatMod("fruit_graphite");
	public static final Item LUDICRITE_FRUIT = new ItemFruitCompatMod("fruit_ludicrite");
	public static final Item ENDERIUM_FRUIT = new ItemFruitCompatMod("fruit_enderium");
	public static final Item LUMIUM_FRUIT = new ItemFruitCompatMod("fruit_lumium");
	public static final Item SIGNALUM_FRUIT = new ItemFruitCompatMod("fruit_signalum");
	public static final Item CONSTANTAN_FRUIT = new ItemFruitCompatMod("fruit_constantan");
	public static final Item MITHRIL_FRUIT = new ItemFruitCompatMod("fruit_mithril");
	public static final Item URANIUM_FRUIT = new ItemFruitCompatMod("fruit_uranium");
	public static final Item APATITE_FRUIT = new ItemFruitCompatMod("fruit_apatite");
	public static final Item SILICON_FRUIT = new ItemFruitCompatMod("fruit_silicon");
	public static final Item DRACONIUM_FRUIT = new ItemFruitCompatMod("fruit_draconium");
	public static final Item DRACONIUM_AWAKENED_FRUIT = new ItemFruitCompatMod("fruit_draconium_awakened");
	public static final Item OSMIUM_FRUIT = new ItemFruitCompatMod("fruit_osmium");
	public static final Item GAIA_FRUIT = new ItemFruitCompatMod("fruit_gaia");

	public static final Item OBSIDIAN_HELMET = new ItemModArmor("obsidian_helmet", ModArmorMaterial.OBSIDIAN, EntityEquipmentSlot.HEAD);
	public static final Item OBSIDIAN_CHEST = new ItemModArmor("obsidian_chestplate", ModArmorMaterial.OBSIDIAN, EntityEquipmentSlot.CHEST);
	public static final Item OBSIDIAN_LEGS = new ItemModArmor("obsidian_leggings", ModArmorMaterial.OBSIDIAN, EntityEquipmentSlot.LEGS);
	public static final Item OBSIDIAN_FEET = new ItemModArmor("obsidian_boots", ModArmorMaterial.OBSIDIAN, EntityEquipmentSlot.FEET);
	public static final Item RENFORCED_HELMET = new ItemModArmor("renforced_helmet", ModArmorMaterial.RENFORCED, EntityEquipmentSlot.HEAD);
	public static final Item RENFORCED_CHEST = new ItemModArmor("renforced_chestplate", ModArmorMaterial.RENFORCED, EntityEquipmentSlot.CHEST);
	public static final Item RENFORCED_LEGS = new ItemModArmor("renforced_leggings", ModArmorMaterial.RENFORCED, EntityEquipmentSlot.LEGS);
	public static final Item RENFORCED_FEET = new ItemModArmor("renforced_boots", ModArmorMaterial.RENFORCED, EntityEquipmentSlot.FEET);
	public static final Item ELEMENTAL_WATER_HELMET = new ItemWaterArmor("elemental_water_helmet", ModArmorMaterial.ELEMENTAL, EntityEquipmentSlot.HEAD);
	public static final Item ELEMENTAL_WATER_CHEST = new ItemWaterArmor("elemental_water_chestplate", ModArmorMaterial.ELEMENTAL, EntityEquipmentSlot.CHEST);
	public static final Item ELEMENTAL_WATER_LEGS = new ItemWaterArmor("elemental_water_leggings", ModArmorMaterial.ELEMENTAL, EntityEquipmentSlot.LEGS);
	public static final Item ELEMENTAL_WATER_FEET = new ItemWaterArmor("elemental_water_boots", ModArmorMaterial.ELEMENTAL, EntityEquipmentSlot.FEET);
	public static final Item ELEMENTAL_FIRE_HELMET = new ItemFireArmor("elemental_fire_helmet", ModArmorMaterial.ELEMENTAL, EntityEquipmentSlot.HEAD);
	public static final Item ELEMENTAL_FIRE_CHEST = new ItemFireArmor("elemental_fire_chestplate", ModArmorMaterial.ELEMENTAL, EntityEquipmentSlot.CHEST);
	public static final Item ELEMENTAL_FIRE_LEGS = new ItemFireArmor("elemental_fire_leggings", ModArmorMaterial.ELEMENTAL, EntityEquipmentSlot.LEGS);
	public static final Item ELEMENTAL_FIRE_FEET = new ItemFireArmor("elemental_fire_boots", ModArmorMaterial.ELEMENTAL, EntityEquipmentSlot.FEET);
	public static final Item ELEMENTAL_EARTH_HELMET = new ItemEarthArmor("elemental_earth_helmet", ModArmorMaterial.ELEMENTAL, EntityEquipmentSlot.HEAD);
	public static final Item ELEMENTAL_EARTH_CHEST = new ItemEarthArmor("elemental_earth_chestplate", ModArmorMaterial.ELEMENTAL, EntityEquipmentSlot.CHEST);
	public static final Item ELEMENTAL_EARTH_LEGS = new ItemEarthArmor("elemental_earth_leggings", ModArmorMaterial.ELEMENTAL, EntityEquipmentSlot.LEGS);
	public static final Item ELEMENTAL_EARTH_FEET = new ItemEarthArmor("elemental_earth_boots", ModArmorMaterial.ELEMENTAL, EntityEquipmentSlot.FEET);
	public static final Item ELEMENTAL_AIR_HELMET = new ItemAirArmor("elemental_air_helmet", ModArmorMaterial.ELEMENTAL, EntityEquipmentSlot.HEAD);
	public static final Item ELEMENTAL_AIR_CHEST = new ItemAirArmor("elemental_air_chestplate", ModArmorMaterial.ELEMENTAL, EntityEquipmentSlot.CHEST);
	public static final Item ELEMENTAL_AIR_LEGS = new ItemAirArmor("elemental_air_leggings", ModArmorMaterial.ELEMENTAL, EntityEquipmentSlot.LEGS);
	public static final Item ELEMENTAL_AIR_FEET = new ItemAirArmor("elemental_air_boots", ModArmorMaterial.ELEMENTAL, EntityEquipmentSlot.FEET);
	public static final Item WATER_GEM_HELMET = new ItemWaterArmor("water_gem_helmet", ModArmorMaterial.GEM, EntityEquipmentSlot.HEAD);
	public static final Item WATER_GEM_CHEST = new ItemWaterArmor("water_gem_chestplate", ModArmorMaterial.GEM, EntityEquipmentSlot.CHEST);
	public static final Item WATER_GEM_LEGS = new ItemWaterArmor("water_gem_leggings", ModArmorMaterial.GEM, EntityEquipmentSlot.LEGS);
	public static final Item WATER_GEM_FEET = new ItemWaterArmor("water_gem_boots", ModArmorMaterial.GEM, EntityEquipmentSlot.FEET);
	public static final Item FIRE_GEM_HELMET = new ItemFireArmor("fire_gem_helmet", ModArmorMaterial.GEM, EntityEquipmentSlot.HEAD);
	public static final Item FIRE_GEM_CHEST = new ItemFireArmor("fire_gem_chestplate", ModArmorMaterial.GEM, EntityEquipmentSlot.CHEST);
	public static final Item FIRE_GEM_LEGS = new ItemFireArmor("fire_gem_leggings", ModArmorMaterial.GEM, EntityEquipmentSlot.LEGS);
	public static final Item FIRE_GEM_FEET = new ItemFireArmor("fire_gem_boots", ModArmorMaterial.GEM, EntityEquipmentSlot.FEET);
	public static final Item EARTH_GEM_HELMET = new ItemEarthArmor("earth_gem_helmet", ModArmorMaterial.GEM, EntityEquipmentSlot.HEAD);
	public static final Item EARTH_GEM_CHEST = new ItemEarthArmor("earth_gem_chestplate", ModArmorMaterial.GEM, EntityEquipmentSlot.CHEST);
	public static final Item EARTH_GEM_LEGS = new ItemEarthArmor("earth_gem_leggings", ModArmorMaterial.GEM, EntityEquipmentSlot.LEGS);
	public static final Item EARTH_GEM_FEET = new ItemEarthArmor("earth_gem_boots", ModArmorMaterial.GEM, EntityEquipmentSlot.FEET);
	public static final Item AIR_GEM_HELMET = new ItemAirArmor("air_gem_helmet", ModArmorMaterial.GEM, EntityEquipmentSlot.HEAD);
	public static final Item AIR_GEM_CHEST = new ItemAirArmor("air_gem_chestplate", ModArmorMaterial.GEM, EntityEquipmentSlot.CHEST);
	public static final Item AIR_GEM_LEGS = new ItemAirArmor("air_gem_leggings", ModArmorMaterial.GEM, EntityEquipmentSlot.LEGS);
	public static final Item AIR_GEM_FEET = new ItemAirArmor("air_gem_boots", ModArmorMaterial.GEM, EntityEquipmentSlot.FEET);
	
	public static final Item ELEMATILIUS = new ItemMod("elematilius");	
	public static final Item FRUIT_START = new ItemMod("fruit_start");	
	public static final Item RELICS_INFINITE_APPLE = new ItemInfiniteApple("infinite_apple");	
	public static final Item RELICS_HORN_PLENTY = new ItemHornPlenty("horn_plenty");	
	public static final Item RELICS_MIDAS_HAND = new ItemMidasHand("midas_hand");		
	public static final Item SCYTHE = new ItemSwordMod("scythe", ModToolMaterial.SCYTHE).setMaxStackSize(1).setNoRepair();	
	
	public static final Item GOLEM_EYE_WATER = new Item().setRegistryName(Reference.MOD_ID, "golem_eye_water").setUnlocalizedName(Reference.MOD_ID + "." + "golem_eye_water").setCreativeTab(Reference.TAB);
	public static final Item GOLEM_EYE_ICE = new Item().setRegistryName(Reference.MOD_ID, "golem_eye_ice").setUnlocalizedName(Reference.MOD_ID + "." + "golem_eye_ice").setCreativeTab(Reference.TAB);
	public static final Item GOLEM_EYE_STEAM = new Item().setRegistryName(Reference.MOD_ID, "golem_eye_steam").setUnlocalizedName(Reference.MOD_ID + "." + "golem_eye_steam").setCreativeTab(Reference.TAB);
	public static final Item GOLEM_EYE_FIRE = new Item().setRegistryName(Reference.MOD_ID, "golem_eye_fire").setUnlocalizedName(Reference.MOD_ID + "." + "golem_eye_fire").setCreativeTab(Reference.TAB);
	public static final Item GOLEM_EYE_LAVA = new Item().setRegistryName(Reference.MOD_ID, "golem_eye_lava").setUnlocalizedName(Reference.MOD_ID + "." + "golem_eye_lava").setCreativeTab(Reference.TAB);
	public static final Item GOLEM_EYE_OBSIDIAN = new Item().setRegistryName(Reference.MOD_ID, "golem_eye_obsidian").setUnlocalizedName(Reference.MOD_ID + "." + "golem_eye_obsidian").setCreativeTab(Reference.TAB);
	public static final Item GOLEM_EYE_EARTH = new Item().setRegistryName(Reference.MOD_ID, "golem_eye_earth").setUnlocalizedName(Reference.MOD_ID + "." + "golem_eye_earth").setCreativeTab(Reference.TAB);
	public static final Item GOLEM_EYE_MUD = new Item().setRegistryName(Reference.MOD_ID, "golem_eye_mud").setUnlocalizedName(Reference.MOD_ID + "." + "golem_eye_mud").setCreativeTab(Reference.TAB);
	public static final Item GOLEM_EYE_DUST = new Item().setRegistryName(Reference.MOD_ID, "golem_eye_dust").setUnlocalizedName(Reference.MOD_ID + "." + "golem_eye_dust").setCreativeTab(Reference.TAB);
	public static final Item GOLEM_EYE_AIR = new Item().setRegistryName(Reference.MOD_ID, "golem_eye_air").setUnlocalizedName(Reference.MOD_ID + "." + "golem_eye_air").setCreativeTab(Reference.TAB);
	public static final Item GOLEM_EYE_SMOKE = new Item().setRegistryName(Reference.MOD_ID, "golem_eye_smoke").setUnlocalizedName(Reference.MOD_ID + "." + "golem_eye_smoke").setCreativeTab(Reference.TAB);
	public static final Item GOLEM_EYE_LIGHTNING = new Item().setRegistryName(Reference.MOD_ID, "golem_eye_lightning").setUnlocalizedName(Reference.MOD_ID + "." + "golem_eye_lightning").setCreativeTab(Reference.TAB);
	
	public static final Item APRICOT_COLLECTOR = new ItemCollector("apricot_collector");	
	public static final Item BANANA_COLLECTOR = new ItemCollector("banana_collector");	
	public static final Item CHERRY_COLLECTOR = new ItemCollector("cherry_collector");	
	public static final Item KIWI_COLLECTOR = new ItemCollector("kiwi_collector");	
	public static final Item LEMON_COLLECTOR = new ItemCollector("lemon_collector");	
	public static final Item ORANGE_COLLECTOR = new ItemCollector("orange_collector");	
	public static final Item PEAR_COLLECTOR = new ItemCollector("pear_collector");	
	
	public static final Item APRICOT_PIE = new ItemFood(8, 5, false).setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "apricot_pie").setUnlocalizedName(Reference.MOD_ID + "." + "apricot_pie");	
	public static final Item BANANA_PIE = new ItemFood(8, 5, false).setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "banana_pie").setUnlocalizedName(Reference.MOD_ID + "." + "banana_pie");	
	public static final Item CHERRY_PIE = new ItemFood(8, 5, false).setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "cherry_pie").setUnlocalizedName(Reference.MOD_ID + "." + "cherry_pie");	
	public static final Item KIWI_PIE = new ItemFood(8, 5, false).setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "kiwi_pie").setUnlocalizedName(Reference.MOD_ID + "." + "kiwi_pie");	
	public static final Item LEMON_PIE = new ItemFood(8, 5, false).setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "lemon_pie").setUnlocalizedName(Reference.MOD_ID + "." + "lemon_pie");	
	public static final Item ORANGE_PIE = new ItemFood(8, 5, false).setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "orange_pie").setUnlocalizedName(Reference.MOD_ID + "." + "orange_pie");	
	public static final Item PEAR_PIE = new ItemFood(8, 5, false).setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "pear_pie").setUnlocalizedName(Reference.MOD_ID + "." + "pear_pie");	
	
	public static final Item APRICOT = new ItemSeedFood(2, 1, ModBlocks.APRICOT_CROP, Blocks.FARMLAND).setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "apricot").setUnlocalizedName(Reference.MOD_ID + "." + "apricot");	
	public static final Item BANANA = new ItemSeedFood(2, 1, ModBlocks.BANANA_CROP, Blocks.FARMLAND).setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "banana").setUnlocalizedName(Reference.MOD_ID + "." + "banana");	
	public static final Item CHERRY = new ItemSeedFood(2, 1, ModBlocks.CHERRY_CROP, Blocks.FARMLAND).setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "cherry").setUnlocalizedName(Reference.MOD_ID + "." + "cherry");	
	public static final Item KIWI = new ItemSeedFood(2, 1, ModBlocks.KIWI_CROP, Blocks.FARMLAND).setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "kiwi").setUnlocalizedName(Reference.MOD_ID + "." + "kiwi");	
	public static final Item LEMON = new ItemSeedFood(2, 1, ModBlocks.LEMON_CROP, Blocks.FARMLAND).setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "lemon").setUnlocalizedName(Reference.MOD_ID + "." + "lemon");	
	public static final Item ORANGE = new ItemSeedFood(2, 1, ModBlocks.ORANGE_CROP, Blocks.FARMLAND).setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "orange").setUnlocalizedName(Reference.MOD_ID + "." + "orange");	
	public static final Item PEAR = new ItemSeedFood(2, 1, ModBlocks.PEAR_CROP, Blocks.FARMLAND).setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "pear").setUnlocalizedName(Reference.MOD_ID + "." + "pear");	
	public static final Item FLOUR = new Item().setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "flour").setUnlocalizedName(Reference.MOD_ID + "." + "flour");
	
	public static final Item BLOCK_REWARD_ITEM = new ItemBlock(ModBlocks.REWARD).setRegistryName(ModBlocks.REWARD.getRegistryName());
	public static final Item BLOCK_GREENHOUSE_ITEM = new GreenHouseItemBlock().setRegistryName(ModBlocks.GREENHOUSE.getRegistryName());
	public static final Item BLOCK_ELEMENTAL_STONE_ITEM = new ItemBlock(ModBlocks.ELEMENTAL_STONE).setRegistryName(ModBlocks.ELEMENTAL_STONE.getRegistryName());
	public static final Item BLOCK_INFUSOR_ITEM = new ItemBlock(ModBlocks.INFUSOR).setCreativeTab(Reference.TAB).setRegistryName(ModBlocks.INFUSOR.getRegistryName());
	public static final Item BLOCK_INFUSOR2_ITEM = new ItemBlock(ModBlocks.INFUSOR2).setCreativeTab(Reference.TAB).setRegistryName(ModBlocks.INFUSOR2.getRegistryName());
	public static final Item BLOCK_INFUSOR2_ELEMENTAL_ITEM = new ItemBlock(ModBlocks.INFUSOR2_ELEMENTAL).setCreativeTab(Reference.TAB).setRegistryName(ModBlocks.INFUSOR2_ELEMENTAL.getRegistryName());
	public static final Item BLOCK_INFUSOR2_WATER_ITEM = new ItemBlock(ModBlocks.INFUSOR2_WATER).setCreativeTab(Reference.TAB).setRegistryName(ModBlocks.INFUSOR2_WATER.getRegistryName());
	public static final Item BLOCK_INFUSOR2_FIRE_ITEM = new ItemBlock(ModBlocks.INFUSOR2_FIRE).setCreativeTab(Reference.TAB).setRegistryName(ModBlocks.INFUSOR2_FIRE.getRegistryName());
	public static final Item BLOCK_INFUSOR2_AIR_ITEM = new ItemBlock(ModBlocks.INFUSOR2_AIR).setCreativeTab(Reference.TAB).setRegistryName(ModBlocks.INFUSOR2_AIR.getRegistryName());
	public static final Item BLOCK_INFUSOR2_EARTH_ITEM = new ItemBlock(ModBlocks.INFUSOR2_EARTH).setCreativeTab(Reference.TAB).setRegistryName(ModBlocks.INFUSOR2_EARTH.getRegistryName());
	public static final Item BLOCK_RITUAL_STAND_ITEM = new ItemBlock(ModBlocks.RITUAL_STAND).setCreativeTab(Reference.TAB).setRegistryName(ModBlocks.RITUAL_STAND.getRegistryName());
	public static final Item BLOCK_RITUAL_STAND_t2_ITEM = new ItemBlock(ModBlocks.RITUAL_STAND_t2).setCreativeTab(Reference.TAB).setRegistryName(ModBlocks.RITUAL_STAND_t2.getRegistryName());
	public static final Item BLOCK_RITUAL_STAND_t3_ITEM = new ItemBlock(ModBlocks.RITUAL_STAND_t3).setCreativeTab(Reference.TAB).setRegistryName(ModBlocks.RITUAL_STAND_t3.getRegistryName());
	public static final Item BLOCK_WATER_BLOCK_ITEM = new ItemBlock(ModBlocks.WATER_BLOCK).setRegistryName(ModBlocks.WATER_BLOCK.getRegistryName());
	public static final Item BLOCK_WATER_GEM_ORE_ITEM = new ItemBlock(ModBlocks.WATER_GEM_ORE).setRegistryName(ModBlocks.WATER_GEM_ORE.getRegistryName());
	public static final Item BLOCK_FIRE_BLOCK_ITEM = new ItemBlock(ModBlocks.FIRE_BLOCK).setRegistryName(ModBlocks.FIRE_BLOCK.getRegistryName());
	public static final Item BLOCK_FIRE_GEM_ORE_ITEM = new ItemBlock(ModBlocks.FIRE_GEM_ORE).setRegistryName(ModBlocks.FIRE_GEM_ORE.getRegistryName());
	public static final Item BLOCK_EARTH_BLOCK_ITEM = new ItemBlock(ModBlocks.EARTH_BLOCK).setRegistryName(ModBlocks.EARTH_BLOCK.getRegistryName());
	public static final Item BLOCK_EARTH_GEM_ORE_ITEM = new ItemBlock(ModBlocks.EARTH_GEM_ORE).setRegistryName(ModBlocks.EARTH_GEM_ORE.getRegistryName());
	public static final Item BLOCK_AIR_BLOCK_ITEM = new ItemBlock(ModBlocks.AIR_BLOCK).setRegistryName(ModBlocks.AIR_BLOCK.getRegistryName());
	public static final Item BLOCK_AIR_GEM_ORE_ITEM = new ItemBlock(ModBlocks.AIR_GEM_ORE).setRegistryName(ModBlocks.AIR_GEM_ORE.getRegistryName());
	
	public static final Item BLOCK_QUICK_ICE_ITEM = new ItemBlock(ModBlocks.QUICK_ICE).setRegistryName(ModBlocks.QUICK_ICE.getRegistryName());	
	public static final Item BLOCK_ICY_PLANT_ITEM = new ItemBlock(ModBlocks.ICY_PLANT).setRegistryName(ModBlocks.ICY_PLANT.getRegistryName());
	public static final Item BLOCK_POISONOUS_ICY_PLANT_ITEM = new ItemBlock(ModBlocks.POISONOUS_ICY_PLANT).setRegistryName(ModBlocks.POISONOUS_ICY_PLANT.getRegistryName());
	public static final Item BLOCK_OBSIDIAN_GROUND_ITEM = new ItemBlock(ModBlocks.OBSIDIAN_GROUND).setRegistryName(ModBlocks.OBSIDIAN_GROUND.getRegistryName());
	public static final Item BLOCK_FIRED_OBSIDIAN_GROUND_ITEM = new ItemBlock(ModBlocks.FIRED_OBSIDIAN_GROUND).setRegistryName(ModBlocks.FIRED_OBSIDIAN_GROUND.getRegistryName());
	public static final Item BLOCK_QUICK_SAND_ITEM = new ItemBlock(ModBlocks.QUICK_SAND).setRegistryName(ModBlocks.QUICK_SAND.getRegistryName());	
	public static final Item BLOCK_CLOUD_ITEM = new ItemBlock(ModBlocks.CLOUD).setRegistryName(ModBlocks.CLOUD.getRegistryName());	
	public static final Item BLOCK_BOUNCE_CLOUD_ITEM = new ItemBlock(ModBlocks.BOUNCE_CLOUD).setRegistryName(ModBlocks.BOUNCE_CLOUD.getRegistryName());	
		
	public static final Item BLOCK_COAL_FURNACE_ITEM = new ItemBlock(ModBlocks.COAL_FURNACE).setRegistryName(ModBlocks.COAL_FURNACE.getRegistryName());
	public static final Item BLOCK_IRON_FURNACE_ITEM = new ItemBlock(ModBlocks.IRON_FURNACE).setRegistryName(ModBlocks.IRON_FURNACE.getRegistryName());
	public static final Item BLOCK_GOLD_FURNACE_ITEM = new ItemBlock(ModBlocks.GOLD_FURNACE).setRegistryName(ModBlocks.GOLD_FURNACE.getRegistryName());
	public static final Item BLOCK_REDSTONE_FURNACE_ITEM = new ItemBlock(ModBlocks.REDSTONE_FURNACE).setRegistryName(ModBlocks.REDSTONE_FURNACE.getRegistryName());
	public static final Item BLOCK_LAPIS_FURNACE_ITEM = new ItemBlock(ModBlocks.LAPIS_FURNACE).setRegistryName(ModBlocks.LAPIS_FURNACE.getRegistryName());
	public static final Item BLOCK_DIAMOND_FURNACE_ITEM = new ItemBlock(ModBlocks.DIAMOND_FURNACE).setRegistryName(ModBlocks.DIAMOND_FURNACE.getRegistryName());
	public static final Item BLOCK_OBSIDIAN_FURNACE_ITEM = new ItemBlock(ModBlocks.OBSIDIAN_FURNACE).setRegistryName(ModBlocks.OBSIDIAN_FURNACE.getRegistryName());
	public static final Item BLOCK_RENFORCED_FURNACE_ITEM = new ItemBlock(ModBlocks.RENFORCED_FURNACE).setRegistryName(ModBlocks.RENFORCED_FURNACE.getRegistryName());
	public static final Item BLOCK_FIRE_FURNACE_ITEM = new ItemBlock(ModBlocks.FIRE_FURNACE).setRegistryName(ModBlocks.FIRE_FURNACE.getRegistryName());
	
	public static final Item ALUMINIUM_ITEM = new ItemMod("aluminium_ingot");
    public static final Item BRASS_ITEM = new ItemMod("brass_ingot");
    public static final Item BRONZE_ITEM = new ItemMod("bronze_ingot");
    public static final Item CHROME_ITEM = new ItemMod("chrome_ingot");
    public static final Item COPPER_ITEM = new ItemMod("copper_ingot");
    public static final Item ELECTRUM_ITEM = new ItemMod("electrum_ingot");
    public static final Item INVAR_ITEM = new ItemMod("invar_ingot");
    public static final Item IRIDIUM_ITEM = new ItemMod("iridium_ingot");
    public static final Item LEAD_ITEM = new ItemMod("lead_ingot");
    public static final Item NICKEL_ITEM = new ItemMod("nickel_ingot");
    public static final Item PLATINIUM_ITEM = new ItemMod("platinium_ingot");
    public static final Item SILVERINGOT_ITEM = new ItemMod("silveringot_ingot");
    public static final Item STEEL_ITEM = new ItemMod("steel_ingot");
    public static final Item TIN_ITEM = new ItemMod("tin_ingot");
    public static final Item TITANIUM_ITEM = new ItemMod("titanium_ingot");
    public static final Item TUNGSTEN_ITEM = new ItemMod("tungsten_ingot");
    public static final Item ZINC_ITEM = new ItemMod("zinc_ingot");
    public static final Item MANASTEEL_ITEM = new ItemMod("ingot_manasteel");
    public static final Item TERRASTEEL_ITEM = new ItemMod("ingot_terrasteel");
    public static final Item MANADIAMOND_ITEM = new ItemMod("mana_diamond");
    public static final Item MANAPEARL_ITEM = new ItemMod("mana_pearl");
    public static final Item ELEMENTIUM_ITEM = new ItemMod("ingot_elementium");
    public static final Item DRAGONSTONE_ITEM = new ItemMod("dragonstone");
    public static final Item GEARWOOD_ITEM = new ItemMod("gearwood");
    public static final Item GEARSTONE_ITEM = new ItemMod("gearstone");
    public static final Item GEARIRON_ITEM = new ItemMod("geariron");
    public static final Item GEARGOLD_ITEM = new ItemMod("geargold");
    public static final Item GEARDIAMOND_ITEM = new ItemMod("geardiamond");   
	public static final Item YELLORIUM_ITEM = new ItemMod("ingot_yellorium");
	public static final Item BLUTONIUM_ITEM = new ItemMod("ingot_blutonium");
	public static final Item CYANITE_ITEM = new ItemMod("ingot_cyanite");
	public static final Item GRAPHITE_ITEM = new ItemMod("ingot_graphite");
	public static final Item LUDICRITE_ITEM = new ItemMod("ingot_ludicrite");
	public static final Item ENDERIUM_ITEM = new ItemMod("ingot_enderium");
	public static final Item LUMIUM_ITEM = new ItemMod("ingot_lumium");
	public static final Item SIGNALUM_ITEM = new ItemMod("ingot_signalum");
	public static final Item CONSTANTAN_ITEM = new ItemMod("ingot_constantan");
	public static final Item MITHRIL_ITEM = new ItemMod("ingot_mithril");
	public static final Item URANIUM_ITEM = new ItemMod("ingot_uranium");
	public static final Item APATITE_ITEM = new ItemMod("gem_apatite");
	public static final Item SILICON_ITEM = new ItemMod("silicon");
	public static final Item DRACONIUM_ITEM = new ItemMod("ingot_draconium");
	public static final Item DRACONIUM_AWAKENED_ITEM = new ItemMod("ingot_draconium_awakened");
	public static final Item OSMIUM_ITEM = new ItemMod("ingot_osmium");
	public static final Item GAIA_ITEM = new ItemMod("gaia_spirit");
	
	public static final Item OBSIDIAN_SWORD = new ItemSwordMod("obsidian_sword", ModToolMaterial.OBSIDIAN);
	public static final Item OBSIDIAN_AXE = new ItemAxeMod("obsidian_axe", ModToolMaterial.OBSIDIAN, 0, 0);
	public static final Item OBSIDIAN_PICKAXE = new ItemPickaxeMod("obsidian_pickaxe", ModToolMaterial.OBSIDIAN);
	public static final Item OBSIDIAN_SHOVEL = new ItemShovelMod("obsidian_shovel", ModToolMaterial.OBSIDIAN);
	public static final Item OBSIDIAN_HOE = new ItemHoeMod("obsidian_hoe", ModToolMaterial.OBSIDIAN);
	public static final Item RENFORCED_SWORD = new ItemSwordMod("renforced_sword", ModToolMaterial.RENFORCED);
	public static final Item RENFORCED_AXE= new ItemAxeMod("renforced_axe", ModToolMaterial.RENFORCED, 0, 0);
	public static final Item RENFORCED_PICKAXE = new ItemPickaxeMod("renforced_pickaxe", ModToolMaterial.RENFORCED);
	public static final Item RENFORCED_SHOVEL = new ItemShovelMod("renforced_shovel", ModToolMaterial.RENFORCED);
	public static final Item RENFORCED_HOE = new ItemHoeMod("renforced_hoe", ModToolMaterial.RENFORCED);
	public static final Item WATER_SWORD = new ItemSwordMod("water_sword", ModToolMaterial.ELEMENTAL);
	public static final Item WATER_AXE= new ItemAxeMod("water_axe", ModToolMaterial.ELEMENTAL, 0, 0);
	public static final Item WATER_PICKAXE = new ItemPickaxeMod("water_pickaxe", ModToolMaterial.ELEMENTAL);
	public static final Item WATER_SHOVEL = new ItemShovelMod("water_shovel", ModToolMaterial.ELEMENTAL);
	public static final Item WATER_HOE = new ItemElementalHoeMod("water_hoe", ModToolMaterial.ELEMENTAL);
	public static final Item FIRE_SWORD = new ItemSwordMod("fire_sword", ModToolMaterial.ELEMENTAL);
	public static final Item FIRE_AXE= new ItemAxeMod("fire_axe", ModToolMaterial.ELEMENTAL, 0, 0);
	public static final Item FIRE_PICKAXE = new ItemPickaxeMod("fire_pickaxe", ModToolMaterial.ELEMENTAL);
	public static final Item FIRE_SHOVEL = new ItemShovelMod("fire_shovel", ModToolMaterial.ELEMENTAL);
	public static final Item FIRE_HOE = new ItemElementalHoeMod("fire_hoe", ModToolMaterial.ELEMENTAL);
	public static final Item EARTH_SWORD = new ItemSwordMod("earth_sword", ModToolMaterial.ELEMENTAL);
	public static final Item EARTH_AXE= new ItemAxeMod("earth_axe", ModToolMaterial.ELEMENTAL, 0, 0);
	public static final Item EARTH_PICKAXE = new ItemPickaxeMod("earth_pickaxe", ModToolMaterial.ELEMENTAL);
	public static final Item EARTH_SHOVEL = new ItemShovelMod("earth_shovel", ModToolMaterial.ELEMENTAL);
	public static final Item EARTH_HOE = new ItemElementalHoeMod("earth_hoe", ModToolMaterial.ELEMENTAL);
	public static final Item AIR_SWORD = new ItemSwordMod("air_sword", ModToolMaterial.ELEMENTAL);
	public static final Item AIR_AXE= new ItemAxeMod("air_axe", ModToolMaterial.ELEMENTAL, 0, 0);
	public static final Item AIR_PICKAXE = new ItemPickaxeMod("air_pickaxe", ModToolMaterial.ELEMENTAL);
	public static final Item AIR_SHOVEL = new ItemShovelMod("air_shovel", ModToolMaterial.ELEMENTAL);
	public static final Item AIR_HOE = new ItemElementalHoeMod("air_hoe", ModToolMaterial.ELEMENTAL);

	public static final Item WOOD_MULTITOOL = new ItemMultitool("wood_multitool", ModToolMaterial.WOOD_MULTI);
	public static final Item STONE_MULTITOOL = new ItemMultitool("stone_multitool", ModToolMaterial.STONE_MULTI);		
	public static final Item IRON_MULTITOOL = new ItemMultitool("iron_multitool", ModToolMaterial.IRON_MULTI);	
	public static final Item GOLD_MULTITOOL = new ItemMultitool("gold_multitool", ModToolMaterial.GOLD_MULTI);	
	public static final Item DIAMOND_MULTITOOL = new ItemMultitool("diamond_multitool", ModToolMaterial.DIAMOND_MULTI);	
	public static final Item OBSIDIAN_MULTITOOL = new ItemMultitool("obsidian_multitool", ModToolMaterial.OBSIDIAN_MULTI);	
	public static final Item RENFORCED_MULTITOOL = new ItemMultitool("renforced_multitool", ModToolMaterial.RENFORCED_MULTI);
	public static final Item ELEMENTAL_MULTITOOL = new ItemMultitool("elemental_multitool", ModToolMaterial.ELEMENTAL_MULTI);
	public static final Item FIRE_MULTITOOL = new ItemElementalMultitool("fire_multitool", ModToolMaterial.ELEMENTAL_MULTI);
	public static final Item WATER_MULTITOOL = new ItemElementalMultitool("water_multitool", ModToolMaterial.ELEMENTAL_MULTI);
	public static final Item EARTH_MULTITOOL = new ItemElementalMultitool("earth_multitool", ModToolMaterial.ELEMENTAL_MULTI);
	public static final Item AIR_MULTITOOL = new ItemElementalMultitool("air_multitool", ModToolMaterial.ELEMENTAL_MULTI);

	public static final Item RAKE = new ItemRake("rake", ToolMaterial.WOOD).setMaxStackSize(1);
	
	public static final Item ELEMENTAL_WATER = new Item().setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "elemental_water").setUnlocalizedName(Reference.MOD_ID + "." + "elemental_water");
	public static final Item ELEMENTAL_FIRE = new Item().setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "elemental_fire").setUnlocalizedName(Reference.MOD_ID + "." + "elemental_fire");
	public static final Item ELEMENTAL_EARTH = new Item().setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "elemental_earth").setUnlocalizedName(Reference.MOD_ID + "." + "elemental_earth");
	public static final Item ELEMENTAL_AIR = new Item().setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "elemental_air").setUnlocalizedName(Reference.MOD_ID + "." + "elemental_air");
	public static final Item POTION_ELEMATILIUS = new Item().setMaxStackSize(1).setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "potion_elematilius").setUnlocalizedName(Reference.MOD_ID + "." + "potion_elematilius");
	public static final Item WATER_GEM = new ItemGem("water_gem");	
	public static final Item FIRE_GEM = new ItemGem("fire_gem");	
	public static final Item EARTH_GEM = new ItemGem("earth_gem");	
	public static final Item AIR_GEM = new ItemGem("air_gem");	
	
	public static final Item POTION_WATER = new Item().setMaxStackSize(1).setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "potion_water").setUnlocalizedName(Reference.MOD_ID + "." + "potion_water");
	public static final Item POTION_FIRE = new Item().setMaxStackSize(1).setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "potion_fire").setUnlocalizedName(Reference.MOD_ID + "." + "potion_fire");
	public static final Item POTION_EARTH = new Item().setMaxStackSize(1).setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "potion_earth").setUnlocalizedName(Reference.MOD_ID + "." + "potion_earth");
	public static final Item POTION_AIR = new Item().setMaxStackSize(1).setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "potion_air").setUnlocalizedName(Reference.MOD_ID + "." + "potion_air");
	
	public static final Item WOOD_PESTLE = new Item().setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "wood_pestle").setUnlocalizedName(Reference.MOD_ID + "." + "wood_pestle");
	public static final Item STONE_PESTLE = new Item().setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "stone_pestle").setUnlocalizedName(Reference.MOD_ID + "." + "stone_pestle").setContainerItem(WOOD_PESTLE);
	public static final Item IRON_PESTLE = new Item().setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "iron_pestle").setUnlocalizedName(Reference.MOD_ID + "." + "iron_pestle").setContainerItem(STONE_PESTLE);
	public static final Item GOLD_PESTLE = new Item().setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "gold_pestle").setUnlocalizedName(Reference.MOD_ID + "." + "gold_pestle").setContainerItem(IRON_PESTLE);
	public static final Item DIAMOND_PESTLE = new Item().setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "diamond_pestle").setUnlocalizedName(Reference.MOD_ID + "." + "diamond_pestle").setContainerItem(GOLD_PESTLE);
	public static final Item OBSIDIAN_PESTLE = new Item().setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "obsidian_pestle").setUnlocalizedName(Reference.MOD_ID + "." + "obsidian_pestle").setContainerItem(DIAMOND_PESTLE);
	public static final Item RENFORCED_PESTLE = new Item().setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "renforced_pestle").setUnlocalizedName(Reference.MOD_ID + "." + "renforced_pestle").setContainerItem(OBSIDIAN_PESTLE);
	public static final Item ELEMENTAL_PESTLE = new Item().setCreativeTab(Reference.TAB).setRegistryName(Reference.MOD_ID, "elemental_pestle").setUnlocalizedName(Reference.MOD_ID + "." + "elemental_pestle").setContainerItem(RENFORCED_PESTLE);
	
    public static void setItemName(Item item, String name)
    {
    	item.setRegistryName(Reference.MOD_ID, name).setUnlocalizedName(Reference.MOD_ID + "." + name);
    }

    @SideOnly(Side.CLIENT)
    @SubscribeEvent
    public static void registerItemModels(ModelRegistryEvent event)
    {   	
    	registerModel(COAL_SEED, 0);
    	registerModel(IRON_SEED, 0);
    	registerModel(GOLD_SEED, 0);
    	registerModel(REDSTONE_SEED, 0);
    	registerModel(LAPIS_SEED, 0);
    	registerModel(DIAMOND_SEED, 0);
    	registerModel(EMERALD_SEED, 0);
    	registerModel(ELEMENTAL_SEED, 0);
    	registerModel(CLAY_SEED, 0);
    	registerModel(GLOWSTONE_SEED, 0);
    	registerModel(QUARTZ_SEED, 0);
    	registerModel(SHARD_SEED, 0);
    	registerModel(CRYSTAL_SEED, 0);
    	registerModel(PAPER_SEED, 0);
    	registerModel(SUGAR_SEED, 0);
    	registerModel(CHARCOAL_SEED, 0);
    	registerModel(FLINT_SEED, 0);
    	registerModel(SNOWBALL_SEED, 0);
    	registerModel(FIREWORK_SEED, 0);
    	registerModel(NETHER_SEED, 0);
    	registerModel(BOTTLE_SEED, 0);
    	registerModel(TOTEM_SEED, 0);
    	registerModel(LEAD2_SEED, 0);
    	registerModel(NAMETAG_SEED, 0);
    	registerModel(XP_SEED, 0);
    	registerModel(ENDER_SEED, 0);
    	registerModel(BONE_SEED, 0);
    	registerModel(EYE_SEED, 0);
    	registerModel(POWDER_SEED, 0);
    	registerModel(BLAZE_SEED, 0);
    	registerModel(GHAST_SEED, 0);
    	registerModel(MAGMA_SEED, 0);
    	registerModel(SHELL_SEED, 0);
    	registerModel(SLIME_SEED, 0);
    	registerModel(STAR_SEED, 0);
    	registerModel(STRING_SEED, 0);
    	registerModel(ZOMBIE_SEED, 0);
    	registerModel(APPLE_SEED, 0);
    	registerModel(GOLDENAPPLE_SEED, 0);
    	registerModel(BREAD_SEED, 0);
    	registerModel(EGG_SEED, 0);
    	registerModel(CLOWNFISH_SEED, 0);
    	registerModel(PUFFERFISH_SEED, 0);
    	registerModel(COOKIE_SEED, 0);
    	registerModel(CHORUS_SEED, 0);
    	registerModel(RAWPORC_SEED, 0);
    	registerModel(RAWBEEF_SEED, 0);
    	registerModel(FISH_SEED, 0);
    	registerModel(SALMON_SEED, 0);
    	registerModel(RAWCHICKEN_SEED, 0);
    	registerModel(RAWRABBIT_SEED, 0);
    	registerModel(RAWMUTTON_SEED, 0);
    	registerModel(ORANGE_SEED, 0); 
    	registerModel(MAGENTA_SEED, 0);
    	registerModel(LIGHTBLUE_SEED, 0);
    	registerModel(YELLOW_SEED, 0);
    	registerModel(LIME_SEED, 0);
    	registerModel(PINK_SEED, 0);
    	registerModel(GRAY_SEED, 0);
    	registerModel(SILVER_SEED, 0);
    	registerModel(CYAN_SEED, 0);
    	registerModel(PURPLE_SEED, 0);
    	registerModel(BROWN_SEED, 0);
    	registerModel(GREEN_SEED, 0);
    	registerModel(RED_SEED, 0);
    	registerModel(BLACK_SEED, 0);		
    	registerModel(VINE_SEED, 0);
    	registerModel(LILYPAD_SEED, 0);
    	registerModel(TALLGRASS_SEED, 0);
    	registerModel(LARGEFERN_SEED, 0);
    	registerModel(BUSH_SEED, 0);
    	registerModel(GRASS1_SEED, 0);
    	registerModel(FERN_SEED, 0);
    	registerModel(OAK_SEED, 0);
    	registerModel(BIRCH_SEED, 0);
    	registerModel(SPRUCE_SEED, 0);
    	registerModel(JUNGLE_SEED, 0);
    	registerModel(DARKOAK_SEED, 0);
    	registerModel(ACACIA_SEED, 0);
    	registerModel(LEATHER_SEED, 0);
    	registerModel(FEATHER_SEED, 0);
    	registerModel(HIDE_SEED, 0);
    	registerModel(FOOT_SEED, 0);

    	registerModel(COAL_SEED_STEM, 0);
    	registerModel(IRON_SEED_STEM, 0);
    	registerModel(GOLD_SEED_STEM ,0);
    	registerModel(REDSTONE_SEED_STEM ,0);
    	registerModel(LAPIS_SEED_STEM ,0);
    	registerModel(DIAMOND_SEED_STEM ,0);
    	registerModel(EMERALD_SEED_STEM ,0);
    	registerModel(SPONGE_SEED_STEM ,0);
    	registerModel(GLASS_SEED_STEM ,0);
    	registerModel(BRICK_SEED_STEM ,0);
    	registerModel(BOOKSHELF_SEED_STEM ,0);
    	registerModel(ICE_SEED_STEM ,0);
    	registerModel(SNOW_SEED_STEM ,0);
    	registerModel(CLAY_SEED_STEM ,0);
    	registerModel(SOULSAND_SEED_STEM ,0);
    	registerModel(GLOWSTONE_SEED_STEM ,0);
    	registerModel(NETHER_SEED_STEM ,0);
    	registerModel(QUARTZ_SEED_STEM ,0);
    	registerModel(SEALANTERN_SEED_STEM ,0);
    	registerModel(PACKEDICE_SEED_STEM ,0);
    	registerModel(MAGMA_SEED_STEM ,0);
    	registerModel(NETHERWART_SEED_STEM ,0);
    	registerModel(BONE_SEED_STEM ,0);
    	registerModel(OBSIDIAN_SEED_STEM ,0);
    	registerModel(END_SEED_STEM ,0);
    	registerModel(ELEMENTAL_SEED_STEM ,0);
    	
       	registerModel(ALUMINIUM_SEED, 0);
        registerModel(BRASS_SEED, 0);
        registerModel(BRONZE_SEED, 0);
        registerModel(CHROME_SEED, 0);
        registerModel(COPPER_SEED, 0);
        registerModel(ELECTRUM_SEED, 0);
        registerModel(INVAR_SEED, 0);
        registerModel(IRIDIUM_SEED, 0);
        registerModel(LEAD_SEED, 0);
        registerModel(NICKEL_SEED, 0);
        registerModel(PLATINIUM_SEED, 0);
        registerModel(SILVERINGOT_SEED, 0);
        registerModel(STEEL_SEED, 0);
        registerModel(TIN_SEED, 0);
        registerModel(TITANIUM_SEED, 0);
        registerModel(TUNGSTEN_SEED, 0);
        registerModel(ZINC_SEED, 0);
        registerModel(MANASTEEL_SEED, 0);
        registerModel(TERRASTEEL_SEED, 0);
        registerModel(MANADIAMOND_SEED, 0);
        registerModel(MANAPEARL_SEED, 0);
        registerModel(ELEMENTIUM_SEED, 0);
        registerModel(DRAGONSTONE_SEED, 0);
        registerModel(GEARWOOD_SEED, 0);
        registerModel(GEARSTONE_SEED, 0);
        registerModel(GEARIRON_SEED, 0);
        registerModel(GEARGOLD_SEED, 0);
        registerModel(GEARDIAMOND_SEED, 0);   
    	registerModel(YELLORIUM_SEED, 0);
    	registerModel(BLUTONIUM_SEED, 0);
    	registerModel(CYANITE_SEED, 0);
    	registerModel(GRAPHITE_SEED, 0);
    	registerModel(LUDICRITE_SEED, 0);
    	registerModel(ENDERIUM_SEED, 0);
    	registerModel(LUMIUM_SEED, 0);
    	registerModel(SIGNALUM_SEED, 0);
    	registerModel(CONSTANTAN_SEED, 0);
    	registerModel(MITHRIL_SEED, 0);
    	registerModel(URANIUM_SEED, 0);
    	registerModel(APATITE_SEED, 0);
    	registerModel(SILICON_SEED, 0);
    	registerModel(DRACONIUM_SEED, 0);
    	registerModel(DRACONIUM_AWAKENED_SEED, 0);
    	registerModel(OSMIUM_SEED, 0);
    	registerModel(GAIA_SEED, 0);
    	
    	registerModel(COAL_FRUIT, 0);
    	registerModel(IRON_FRUIT, 0);
    	registerModel(GOLD_FRUIT, 0);
    	registerModel(REDSTONE_FRUIT, 0);
    	registerModel(LAPIS_FRUIT, 0);
    	registerModel(DIAMOND_FRUIT, 0);
    	registerModel(EMERALD_FRUIT, 0);
    	registerModel(ELEMENTAL_FRUIT, 0);
    	registerModel(CLAY_FRUIT, 0);
    	registerModel(GLOWSTONE_FRUIT, 0);
    	registerModel(QUARTZ_FRUIT, 0);
    	registerModel(SHARD_FRUIT, 0);
    	registerModel(CRYSTAL_FRUIT, 0);
    	registerModel(PAPER_FRUIT, 0);
    	registerModel(SUGAR_FRUIT, 0);
    	registerModel(CHARCOAL_FRUIT, 0);
    	registerModel(FLINT_FRUIT, 0);
    	registerModel(SNOWBALL_FRUIT, 0);
    	registerModel(FIREWORK_FRUIT, 0);
    	registerModel(NETHER_FRUIT, 0);
    	registerModel(BOTTLE_FRUIT, 0);
    	registerModel(TOTEM_FRUIT, 0);
    	registerModel(LEAD2_FRUIT, 0);
    	registerModel(NAMETAG_FRUIT, 0);
    	registerModel(XP_FRUIT, 0); 	
    	registerModel(ENDER_FRUIT, 0);
    	registerModel(BONE_FRUIT, 0);
    	registerModel(EYE_FRUIT, 0);
    	registerModel(POWDER_FRUIT, 0);
    	registerModel(BLAZE_FRUIT, 0);
    	registerModel(GHAST_FRUIT, 0);
    	registerModel(MAGMA_FRUIT, 0);
    	registerModel(SHELL_FRUIT, 0);
    	registerModel(SLIME_FRUIT, 0);
    	registerModel(STAR_FRUIT, 0);
    	registerModel(STRING_FRUIT, 0);
    	registerModel(ZOMBIE_FRUIT, 0);    	
    	registerModel(APPLE_FRUIT, 0);
    	registerModel(GOLDENAPPLE_FRUIT, 0);
    	registerModel(BREAD_FRUIT, 0);
    	registerModel(EGG_FRUIT, 0);
    	registerModel(CLOWNFISH_FRUIT, 0);
    	registerModel(PUFFERFISH_FRUIT, 0);
    	registerModel(COOKIE_FRUIT, 0);
    	registerModel(CHORUS_FRUIT, 0);
    	registerModel(RAWPORC_FRUIT, 0);
    	registerModel(RAWBEEF_FRUIT, 0);
    	registerModel(FISH_FRUIT, 0);
    	registerModel(SALMON_FRUIT, 0);
    	registerModel(RAWCHICKEN_FRUIT, 0);
    	registerModel(RAWRABBIT_FRUIT, 0);
    	registerModel(RAWMUTTON_FRUIT, 0);
    	registerModel(ORANGE_FRUIT, 0); 
    	registerModel(MAGENTA_FRUIT, 0);
    	registerModel(LIGHTBLUE_FRUIT, 0);
    	registerModel(YELLOW_FRUIT, 0);
    	registerModel(LIME_FRUIT, 0);
    	registerModel(PINK_FRUIT, 0);
    	registerModel(GRAY_FRUIT, 0);
    	registerModel(SILVER_FRUIT, 0);
    	registerModel(CYAN_FRUIT, 0);
    	registerModel(PURPLE_FRUIT, 0);
    	registerModel(BROWN_FRUIT, 0);
    	registerModel(GREEN_FRUIT, 0);
    	registerModel(RED_FRUIT, 0);
    	registerModel(BLACK_FRUIT, 0);		
    	registerModel(VINE_FRUIT, 0);
    	registerModel(LILYPAD_FRUIT, 0);
    	registerModel(TALLGRASS_FRUIT, 0);
    	registerModel(LARGEFERN_FRUIT, 0);
    	registerModel(BUSH_FRUIT, 0);
    	registerModel(GRASS1_FRUIT, 0);
    	registerModel(FERN_FRUIT, 0);
    	registerModel(OAK_FRUIT, 0);
    	registerModel(BIRCH_FRUIT, 0);
    	registerModel(SPRUCE_FRUIT, 0);
    	registerModel(JUNGLE_FRUIT, 0);
    	registerModel(DARKOAK_FRUIT, 0);
    	registerModel(ACACIA_FRUIT, 0);
    	registerModel(LEATHER_FRUIT, 0);
    	registerModel(FEATHER_FRUIT, 0);
    	registerModel(HIDE_FRUIT, 0);
    	registerModel(FOOT_FRUIT, 0);
    	
    	registerModel(ALUMINIUM_FRUIT, 0);
        registerModel(BRASS_FRUIT, 0);
        registerModel(BRONZE_FRUIT, 0);
        registerModel(CHROME_FRUIT, 0);
        registerModel(COPPER_FRUIT, 0);
        registerModel(ELECTRUM_FRUIT, 0);
        registerModel(INVAR_FRUIT, 0);
        registerModel(IRIDIUM_FRUIT, 0);
        registerModel(LEAD_FRUIT, 0);
        registerModel(NICKEL_FRUIT, 0);
        registerModel(PLATINIUM_FRUIT, 0);
        registerModel(SILVERINGOT_FRUIT, 0);
        registerModel(STEEL_FRUIT, 0);
        registerModel(TIN_FRUIT, 0);
        registerModel(TITANIUM_FRUIT, 0);
        registerModel(TUNGSTEN_FRUIT, 0);
        registerModel(ZINC_FRUIT, 0);
        registerModel(MANASTEEL_FRUIT, 0);
        registerModel(TERRASTEEL_FRUIT, 0);
        registerModel(MANADIAMOND_FRUIT, 0);
        registerModel(MANAPEARL_FRUIT, 0);
        registerModel(ELEMENTIUM_FRUIT, 0);
        registerModel(DRAGONSTONE_FRUIT, 0);
        registerModel(GEARWOOD_FRUIT, 0);
        registerModel(GEARSTONE_FRUIT, 0);
        registerModel(GEARIRON_FRUIT, 0);
        registerModel(GEARGOLD_FRUIT, 0);
        registerModel(GEARDIAMOND_FRUIT, 0);   
    	registerModel(YELLORIUM_FRUIT, 0);
    	registerModel(BLUTONIUM_FRUIT, 0);
    	registerModel(CYANITE_FRUIT, 0);
    	registerModel(GRAPHITE_FRUIT, 0);
    	registerModel(LUDICRITE_FRUIT, 0);
    	registerModel(ENDERIUM_FRUIT, 0);
    	registerModel(LUMIUM_FRUIT, 0);
    	registerModel(SIGNALUM_FRUIT, 0);
    	registerModel(CONSTANTAN_FRUIT, 0);
    	registerModel(MITHRIL_FRUIT, 0);
    	registerModel(URANIUM_FRUIT, 0);
    	registerModel(APATITE_FRUIT, 0);
    	registerModel(SILICON_FRUIT, 0);
    	registerModel(DRACONIUM_FRUIT, 0);
    	registerModel(DRACONIUM_AWAKENED_FRUIT, 0);
    	registerModel(OSMIUM_FRUIT, 0);
    	registerModel(GAIA_FRUIT, 0);

    	registerModel(OBSIDIAN_HELMET, 0);
		registerModel(OBSIDIAN_CHEST, 0);
		registerModel(OBSIDIAN_LEGS, 0);
		registerModel(OBSIDIAN_FEET, 0);
		registerModel(RENFORCED_HELMET, 0);
		registerModel(RENFORCED_CHEST, 0);
		registerModel(RENFORCED_LEGS, 0);
		registerModel(RENFORCED_FEET, 0);
		registerModel(ELEMENTAL_WATER_HELMET, 0);
		registerModel(ELEMENTAL_WATER_CHEST, 0);
		registerModel(ELEMENTAL_WATER_LEGS, 0);
		registerModel(ELEMENTAL_WATER_FEET, 0);
		registerModel(ELEMENTAL_FIRE_HELMET, 0);
		registerModel(ELEMENTAL_FIRE_CHEST, 0);
		registerModel(ELEMENTAL_FIRE_LEGS, 0);
		registerModel(ELEMENTAL_FIRE_FEET, 0);
		registerModel(ELEMENTAL_EARTH_HELMET, 0);
		registerModel(ELEMENTAL_EARTH_CHEST, 0);
		registerModel(ELEMENTAL_EARTH_LEGS, 0);
		registerModel(ELEMENTAL_EARTH_FEET, 0);
		registerModel(ELEMENTAL_AIR_HELMET, 0);
		registerModel(ELEMENTAL_AIR_CHEST, 0);
		registerModel(ELEMENTAL_AIR_LEGS, 0);
		registerModel(ELEMENTAL_AIR_FEET, 0);
		registerModel(WATER_GEM_HELMET, 0);
		registerModel(WATER_GEM_CHEST, 0);
		registerModel(WATER_GEM_LEGS, 0);
		registerModel(WATER_GEM_FEET, 0);
		registerModel(FIRE_GEM_HELMET, 0);
		registerModel(FIRE_GEM_CHEST, 0);
		registerModel(FIRE_GEM_LEGS, 0);
		registerModel(FIRE_GEM_FEET, 0);
		registerModel(EARTH_GEM_HELMET, 0);
		registerModel(EARTH_GEM_CHEST, 0);
		registerModel(EARTH_GEM_LEGS, 0);
		registerModel(EARTH_GEM_FEET, 0);
		registerModel(AIR_GEM_HELMET, 0);
		registerModel(AIR_GEM_CHEST, 0);
		registerModel(AIR_GEM_LEGS, 0);
		registerModel(AIR_GEM_FEET, 0);

    	registerModel(ELEMATILIUS, 0);
    	registerModel(FRUIT_START, 0);
    	registerModel(RELICS_INFINITE_APPLE, 0);
    	registerModel(RELICS_HORN_PLENTY, 0);
    	registerModel(RELICS_MIDAS_HAND, 0);
    	registerModel(SCYTHE, 0);

    	registerModel(GOLEM_EYE_WATER, 0);
    	registerModel(GOLEM_EYE_ICE, 0);
    	registerModel(GOLEM_EYE_STEAM, 0);
    	registerModel(GOLEM_EYE_FIRE, 0);
    	registerModel(GOLEM_EYE_LAVA, 0);
    	registerModel(GOLEM_EYE_OBSIDIAN, 0);
    	registerModel(GOLEM_EYE_EARTH, 0);
    	registerModel(GOLEM_EYE_MUD, 0);
    	registerModel(GOLEM_EYE_DUST, 0);
    	registerModel(GOLEM_EYE_AIR, 0);
    	registerModel(GOLEM_EYE_SMOKE, 0);
    	registerModel(GOLEM_EYE_LIGHTNING, 0);
    	
    	registerModel(APRICOT_COLLECTOR, 0);
    	registerModel(BANANA_COLLECTOR, 0);
    	registerModel(CHERRY_COLLECTOR, 0);
    	registerModel(KIWI_COLLECTOR, 0);
    	registerModel(LEMON_COLLECTOR, 0);
    	registerModel(ORANGE_COLLECTOR, 0);
    	registerModel(PEAR_COLLECTOR, 0);

    	registerModel(APRICOT, 0);
    	registerModel(BANANA, 0);
    	registerModel(CHERRY, 0);
    	registerModel(KIWI, 0);
    	registerModel(LEMON, 0);
    	registerModel(ORANGE, 0);
    	registerModel(PEAR, 0);
    	registerModel(FLOUR, 0);
    	
    	registerModel(APRICOT_PIE, 0);
    	registerModel(BANANA_PIE, 0);
    	registerModel(CHERRY_PIE, 0);
    	registerModel(KIWI_PIE, 0);
    	registerModel(LEMON_PIE, 0);
    	registerModel(ORANGE_PIE, 0);
    	registerModel(PEAR_PIE, 0);

    	registerModel(BLOCK_REWARD_ITEM, 0);
    	registerModel(BLOCK_GREENHOUSE_ITEM, 0);
    	registerModel(BLOCK_ELEMENTAL_STONE_ITEM, 0);
    	registerModel(BLOCK_INFUSOR_ITEM, 0);
    	registerModel(BLOCK_INFUSOR2_ITEM, 0);
    	registerModel(BLOCK_INFUSOR2_ELEMENTAL_ITEM, 0);
    	registerModel(BLOCK_INFUSOR2_WATER_ITEM, 0);
    	registerModel(BLOCK_INFUSOR2_FIRE_ITEM, 0);
    	registerModel(BLOCK_INFUSOR2_AIR_ITEM, 0);
    	registerModel(BLOCK_INFUSOR2_EARTH_ITEM, 0);
    	registerModel(BLOCK_RITUAL_STAND_ITEM, 0);
    	registerModel(BLOCK_RITUAL_STAND_t2_ITEM, 0);
    	registerModel(BLOCK_RITUAL_STAND_t3_ITEM, 0);
    	registerModel(BLOCK_WATER_BLOCK_ITEM, 0);
    	registerModel(BLOCK_WATER_GEM_ORE_ITEM, 0);
    	registerModel(BLOCK_FIRE_BLOCK_ITEM, 0);
    	registerModel(BLOCK_FIRE_GEM_ORE_ITEM, 0);
    	registerModel(BLOCK_EARTH_BLOCK_ITEM, 0);
    	registerModel(BLOCK_EARTH_GEM_ORE_ITEM, 0);
    	registerModel(BLOCK_AIR_BLOCK_ITEM, 0);
    	registerModel(BLOCK_AIR_GEM_ORE_ITEM, 0);

    	registerModel(BLOCK_QUICK_ICE_ITEM, 0);
    	registerModel(BLOCK_ICY_PLANT_ITEM, 0);
    	registerModel(BLOCK_POISONOUS_ICY_PLANT_ITEM, 0);
    	registerModel(BLOCK_OBSIDIAN_GROUND_ITEM, 0);
    	registerModel(BLOCK_FIRED_OBSIDIAN_GROUND_ITEM, 0);
    	registerModel(BLOCK_QUICK_SAND_ITEM, 0);
    	registerModel(BLOCK_CLOUD_ITEM, 0);
    	registerModel(BLOCK_BOUNCE_CLOUD_ITEM, 0);
    	
    	registerModel(BLOCK_COAL_FURNACE_ITEM, 0);
    	registerModel(BLOCK_IRON_FURNACE_ITEM, 0);
    	registerModel(BLOCK_GOLD_FURNACE_ITEM, 0);
    	registerModel(BLOCK_REDSTONE_FURNACE_ITEM, 0);
    	registerModel(BLOCK_LAPIS_FURNACE_ITEM, 0);
    	registerModel(BLOCK_DIAMOND_FURNACE_ITEM, 0);
    	registerModel(BLOCK_OBSIDIAN_FURNACE_ITEM, 0);
    	registerModel(BLOCK_RENFORCED_FURNACE_ITEM, 0);
    	registerModel(BLOCK_FIRE_FURNACE_ITEM, 0);
    	
    	registerModel(ALUMINIUM_ITEM, 0);
        registerModel(BRASS_ITEM, 0);
        registerModel(BRONZE_ITEM, 0);
        registerModel(CHROME_ITEM, 0);
        registerModel(COPPER_ITEM, 0);
        registerModel(ELECTRUM_ITEM, 0);
        registerModel(INVAR_ITEM, 0);
        registerModel(IRIDIUM_ITEM, 0);
        registerModel(LEAD_ITEM, 0);
        registerModel(NICKEL_ITEM, 0);
        registerModel(PLATINIUM_ITEM, 0);
        registerModel(SILVERINGOT_ITEM, 0);
        registerModel(STEEL_ITEM, 0);
        registerModel(TIN_ITEM, 0);
        registerModel(TITANIUM_ITEM, 0);
        registerModel(TUNGSTEN_ITEM, 0);
        registerModel(ZINC_ITEM, 0);
        registerModel(MANASTEEL_ITEM, 0);
        registerModel(TERRASTEEL_ITEM, 0);
        registerModel(MANADIAMOND_ITEM, 0);
        registerModel(MANAPEARL_ITEM, 0);
        registerModel(ELEMENTIUM_ITEM, 0);
        registerModel(DRAGONSTONE_ITEM, 0);
        registerModel(GEARWOOD_ITEM, 0);
        registerModel(GEARSTONE_ITEM, 0);
        registerModel(GEARIRON_ITEM, 0);
        registerModel(GEARGOLD_ITEM, 0);
        registerModel(GEARDIAMOND_ITEM, 0);  
    	registerModel(YELLORIUM_ITEM, 0);
    	registerModel(BLUTONIUM_ITEM, 0);
    	registerModel(CYANITE_ITEM, 0);
    	registerModel(GRAPHITE_ITEM, 0);
    	registerModel(LUDICRITE_ITEM, 0);
    	registerModel(ENDERIUM_ITEM, 0);
    	registerModel(LUMIUM_ITEM, 0);
    	registerModel(SIGNALUM_ITEM, 0);
    	registerModel(CONSTANTAN_ITEM, 0);
    	registerModel(MITHRIL_ITEM, 0);
    	registerModel(URANIUM_ITEM, 0);
    	registerModel(APATITE_ITEM, 0);
    	registerModel(SILICON_ITEM, 0);
    	registerModel(DRACONIUM_ITEM, 0);
    	registerModel(DRACONIUM_AWAKENED_ITEM, 0);
    	registerModel(OSMIUM_ITEM, 0);
    	registerModel(GAIA_ITEM, 0);

    	registerModel(OBSIDIAN_SWORD, 0);
    	registerModel(OBSIDIAN_AXE, 0);
    	registerModel(OBSIDIAN_PICKAXE, 0);
    	registerModel(OBSIDIAN_SHOVEL, 0);
    	registerModel(OBSIDIAN_HOE, 0);
    	registerModel(RENFORCED_SWORD, 0);
		registerModel(RENFORCED_AXE, 0);
		registerModel(RENFORCED_PICKAXE, 0);
		registerModel(RENFORCED_SHOVEL, 0);
		registerModel(RENFORCED_HOE, 0);
    	registerModel(WATER_SWORD, 0);
		registerModel(WATER_AXE, 0);
		registerModel(WATER_PICKAXE, 0);
		registerModel(WATER_SHOVEL, 0);
		registerModel(WATER_HOE, 0);
    	registerModel(FIRE_SWORD, 0);
		registerModel(FIRE_AXE, 0);
		registerModel(FIRE_PICKAXE, 0);
		registerModel(FIRE_SHOVEL, 0);
		registerModel(FIRE_HOE, 0);
    	registerModel(EARTH_SWORD, 0);
		registerModel(EARTH_AXE, 0);
		registerModel(EARTH_PICKAXE, 0);
		registerModel(EARTH_SHOVEL, 0);
		registerModel(EARTH_HOE, 0);
    	registerModel(AIR_SWORD, 0);
		registerModel(AIR_AXE, 0);
		registerModel(AIR_PICKAXE, 0);
		registerModel(AIR_SHOVEL, 0);
		registerModel(AIR_HOE, 0);

    	registerModel(ELEMENTAL_WATER, 0);
    	registerModel(ELEMENTAL_FIRE, 0);
    	registerModel(ELEMENTAL_EARTH, 0);
    	registerModel(ELEMENTAL_AIR, 0);

    	registerModel(WATER_GEM, 0);
    	registerModel(FIRE_GEM, 0);
    	registerModel(EARTH_GEM, 0);
    	registerModel(AIR_GEM, 0);

    	registerModel(POTION_ELEMATILIUS, 0);
    	registerModel(POTION_WATER, 0);
    	registerModel(POTION_FIRE, 0);
    	registerModel(POTION_EARTH, 0);
    	registerModel(POTION_AIR, 0);

    	registerModel(WOOD_MULTITOOL, 0);
    	registerModel(STONE_MULTITOOL, 0);
    	registerModel(IRON_MULTITOOL, 0);
    	registerModel(GOLD_MULTITOOL, 0);
    	registerModel(DIAMOND_MULTITOOL, 0);
    	registerModel(OBSIDIAN_MULTITOOL, 0);
    	registerModel(RENFORCED_MULTITOOL, 0);
    	registerModel(ELEMENTAL_MULTITOOL, 0);
    	registerModel(FIRE_MULTITOOL, 0);
    	registerModel(WATER_MULTITOOL, 0);
    	registerModel(EARTH_MULTITOOL, 0);
    	registerModel(AIR_MULTITOOL, 0);
    	
    	registerModel(RAKE, 0);
    	
    	registerModel(WOOD_PESTLE, 0);
    	registerModel(STONE_PESTLE, 0);
    	registerModel(IRON_PESTLE, 0);
    	registerModel(GOLD_PESTLE, 0);
    	registerModel(DIAMOND_PESTLE, 0);
    	registerModel(OBSIDIAN_PESTLE, 0);
    	registerModel(RENFORCED_PESTLE, 0);
    	registerModel(ELEMENTAL_PESTLE, 0);
    	

    }

    @SideOnly(Side.CLIENT)
    public static void registerModel(Item item, int metadata)
    {
    	 if (metadata < 0) metadata = 0;
    	    String resourceName = item.getUnlocalizedName().substring(5).replace('.', ':');
    	    if (metadata > 0) resourceName += "_m" + String.valueOf(metadata);
    	    ModelLoader.setCustomModelResourceLocation(item, metadata, new ModelResourceLocation(resourceName, "inventory"));
    }
}
